// metaclouds-frontend-vue/src/pages/Dashboard.vue
<template>
  <div class="mc-page">
    <div class="mc-page-head">
      <div class="mc-page-head-main">
        <h1 class="mc-page-title">算力总览</h1>
        <p class="mc-page-desc">{{ rangeLabel }} · 实时掌握全平台算力水位、作业吞吐与风险告警</p>
      </div>
      <div class="mc-page-head-extra">
        <el-radio-group v-model="range" size="small">
          <el-radio-button value="today">今日</el-radio-button>
          <el-radio-button value="7d">近 7 天</el-radio-button>
          <el-radio-button value="30d">近 30 天</el-radio-button>
        </el-radio-group>
        <el-button :icon="Refresh" @click="refetchAll">刷新</el-button>
      </div>
    </div>

    <PageState
      :loading="anyLoading"
      :error="anyError"
      :data="hasData"
      empty-text="暂无看板数据"
      retry-text="重新加载"
      @retry="refetchAll"
    >
      <!-- KPI 卡片行 -->
      <div class="kpi-grid">
        <div v-for="card in kpiCards" :key="card.title" class="kpi-card">
          <div class="kpi-icon" :style="{ background: card.bg }">
            <el-icon :size="22" color="#fff"><component :is="card.icon" /></el-icon>
          </div>
          <div class="kpi-body">
            <div class="kpi-title">{{ card.title }}</div>
            <div class="kpi-value">
              {{ card.value }}<span class="kpi-suffix">{{ card.suffix }}</span>
            </div>
            <div class="kpi-footer" v-html="card.footer"></div>
          </div>
        </div>
      </div>

      <!-- 三个饼图 -->
      <el-row :gutter="16" class="mc-mt">
        <el-col :xs="24" :sm="24" :md="8">
          <el-card shadow="never">
            <template #header>
              <div class="chart-card-head">
                <span>资源分布</span>
                <span class="chart-card-extra">GPU 卡</span>
              </div>
            </template>
            <div v-if="gpuTotal > 0" ref="resourceChartRef" class="chart-box" />
            <el-empty v-else description="暂无资源数据" :image-size="80" />
          </el-card>
        </el-col>
        <el-col :xs="24" :sm="24" :md="8">
          <el-card shadow="never">
            <template #header>
              <div class="chart-card-head">
                <span>作业状态分布</span>
                <span class="chart-card-extra">共 {{ totalJobs }} 个</span>
              </div>
            </template>
            <div v-if="jobStatusData.length > 0" ref="jobChartRef" class="chart-box" />
            <el-empty v-else description="还没有作业" :image-size="80" />
          </el-card>
        </el-col>
        <el-col :xs="24" :sm="24" :md="8">
          <el-card shadow="never">
            <template #header>
              <div class="chart-card-head">
                <span>GPU 厂商分布</span>
                <span class="chart-card-extra">共 {{ gpuDevices.length }} 张</span>
              </div>
            </template>
            <div v-if="gpuVendorData.length > 0" ref="vendorChartRef" class="chart-box" />
            <el-empty v-else description="暂无 GPU 设备" :image-size="80" />
          </el-card>
        </el-col>
      </el-row>

      <!-- 最近告警 -->
      <el-card shadow="never" class="mc-mt">
        <template #header>
          <div class="chart-card-head">
            <span>最近告警</span>
            <span class="chart-card-extra">按严重程度排序</span>
          </div>
        </template>
        <el-empty v-if="alertsData.length === 0" description="暂无告警，系统运行正常" :image-size="80" />
        <ul v-else class="alert-list">
          <li v-for="item in topAlerts" :key="item.id" class="alert-item">
            <div class="alert-line">
              <span class="mc-status" :class="alertLevelClass(item.level)">
                <i class="mc-status-dot" :style="{ background: alertColor(item.level) }" />
                {{ alertText(item.level) }}
              </span>
              <span class="alert-message">{{ item.message || item.details || '未知告警' }}</span>
            </div>
            <div class="alert-detail">{{ item.details || item.message || '暂无详情' }}</div>
          </li>
        </ul>
      </el-card>
    </PageState>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import * as echarts from 'echarts'
import { Refresh, Coin, Cloudy, Timer, Bell, UserFilled, Grid, Operation } from '@element-plus/icons-vue'
import PageState from '@/components/PageState.vue'
import {
  clusterApi,
  resourceApi,
  jobApi,
  monitoringApi,
  gpuApi,
  partitionApi,
  schedulerApi,
  tenantApi,
} from '@/api'
import { useFetch } from '@/utils/useFetch'
import type { Cluster, Resource, Job, Alert, GPUDevice, Partition, SchedulerIntegration, Tenant, GPUVendor } from '@/types'

// ---------- 数据加载 ----------
const clusters = useFetch<Cluster[]>(() => clusterApi.list())
const resources = useFetch<Resource[]>(() => resourceApi.list())
const jobs = useFetch<Job[]>(() => jobApi.list())
const alerts = useFetch<Alert[]>(() => monitoringApi.alerts())
const gpuDevicesF = useFetch<GPUDevice[]>(() => gpuApi.devices({}))
const partitionsF = useFetch<Partition[]>(() => partitionApi.list({}))
const schedulersF = useFetch<SchedulerIntegration[]>(() => schedulerApi.list())
const tenantsF = useFetch<Tenant[]>(() => tenantApi.list())

const clustersData = computed(() => clusters.data.value ?? [])
const resourcesData = computed(() => resources.data.value ?? [])
const jobsData = computed(() => jobs.data.value ?? [])
const alertsData = computed(() => alerts.data.value ?? [])
const gpuDevices = computed(() => gpuDevicesF.data.value ?? [])
const partitions = computed(() => partitionsF.data.value ?? [])
const schedulers = computed(() => schedulersF.data.value ?? [])
const tenants = computed(() => tenantsF.data.value ?? [])

const anyLoading = computed(
  () => clusters.loading.value || resources.loading.value || jobs.loading.value || alerts.loading.value,
)
const anyError = computed(() => {
  const e = clusters.error.value || resources.error.value || jobs.error.value || alerts.error.value
  return e || ''
})
const hasData = computed(
  () => clustersData.value.length + resourcesData.value.length + jobsData.value.length + alertsData.value.length > 0,
)

function refetchAll() {
  clusters.refetch()
  resources.refetch()
  jobs.refetch()
  alerts.refetch()
  gpuDevicesF.refetch()
  partitionsF.refetch()
  schedulersF.refetch()
  tenantsF.refetch()
}

// ---------- 时间范围 ----------
const range = ref<'today' | '7d' | '30d'>('7d')
const rangeLabel = computed(
  () => ({ today: '今日', '7d': '近 7 天', '30d': '近 30 天' })[range.value],
)

// ---------- KPI 计算 ----------
const gpuUsed = computed(() =>
  resourcesData.value.reduce((s, r) => s + (Number(r.used) || 0), 0),
)
const gpuTotal = computed(() =>
  resourcesData.value.reduce((s, r) => s + (Number(r.total) || 0), 0),
)
const utilization = computed(() =>
  gpuTotal.value > 0 ? Math.round((gpuUsed.value / gpuTotal.value) * 100) : 0,
)
const runningJobs = computed(() => jobsData.value.filter((j) => j.status === 'running').length)
const pendingJobs = computed(() => jobsData.value.filter((j) => j.status === 'pending').length)
const totalJobs = computed(() => jobsData.value.length)
const alertCount = computed(() => alertsData.value.length)

const partitionStats = computed(() => ({
  total: partitions.value.length,
  active: partitions.value.filter((p) => p.status === 'active').length,
  maintenance: partitions.value.filter((p) => p.status === 'maintenance').length,
}))
const schedulerStats = computed(() => ({
  total: schedulers.value.length,
  active: schedulers.value.filter((s) => s.status === 'active').length,
  error: schedulers.value.filter((s) => s.status === 'error').length,
}))

const kpiCards = computed(() => [
  {
    title: '集群数量',
    value: clustersData.value.length,
    suffix: ' 个',
    icon: Coin,
    bg: 'linear-gradient(135deg,#2f6bff,#5b8bff)',
    footer: '统一纳管的计算集群',
  },
  {
    title: 'GPU 利用率',
    value: utilization.value,
    suffix: '%',
    icon: Cloudy,
    bg: 'linear-gradient(135deg,#1f52e0,#2f6bff)',
    footer: `<span class="mc-num">已用 ${gpuUsed.value} / 共 ${gpuTotal.value}</span>`,
  },
  {
    title: '运行中作业',
    value: runningJobs.value,
    suffix: ` / ${totalJobs.value}`,
    icon: Timer,
    bg: 'linear-gradient(135deg,#5b8bff,#69b1ff)',
    footer: `排队中 <b class="mc-num">${pendingJobs.value}</b> 个`,
  },
  {
    title: '活跃告警',
    value: alertCount.value,
    suffix: ' 条',
    icon: Bell,
    bg:
      alertCount.value > 0
        ? 'linear-gradient(135deg,#ff5c7a,#ff7a9c)'
        : 'linear-gradient(135deg,#2f6bff,#5b8bff)',
    footer: alertCount.value > 0 ? '<span style="color:var(--mc-danger)">需要关注</span>' : '运行正常',
  },
  {
    title: '租户数量',
    value: tenants.value.length,
    suffix: ' 个',
    icon: UserFilled,
    bg: 'linear-gradient(135deg,#2f6bff,#5b8bff)',
    footer: '多租户资源隔离与配额',
  },
  {
    title: '分区状态',
    value: partitionStats.value.total,
    suffix: ' 个',
    icon: Grid,
    bg: 'linear-gradient(135deg,#2f6bff,#5b8bff)',
    footer: `活跃 ${partitionStats.value.active} · 维护 ${partitionStats.value.maintenance}`,
  },
  {
    title: '调度器集成',
    value: schedulerStats.value.total,
    suffix: ' 个',
    icon: Operation,
    bg: 'linear-gradient(135deg,#1f52e0,#2f6bff)',
    footer: `活跃 ${schedulerStats.value.active}${schedulerStats.value.error > 0 ? ` · 异常 ${schedulerStats.value.error}` : ''}`,
  },
])

// ---------- 图表 ----------
const VENDOR_LABEL: Record<string, string> = {
  nvidia: 'NVIDIA',
  enflame: '燧原',
  moore_threads: '摩尔线程',
  domestic_x: '国产X',
}
const VENDOR_COLOR: Record<string, string> = {
  nvidia: '#76b900',
  enflame: '#2f6bff',
  moore_threads: '#7c5cff',
  domestic_x: '#fa8c16',
}
const STATUS_TEXT: Record<string, string> = {
  running: '运行中',
  pending: '排队中',
  completed: '已完成',
  failed: '失败',
  cancelled: '已取消',
  active: '活跃',
  maintenance: '维护',
  info: '信息',
  warning: '警告',
  error: '错误',
  critical: '严重',
}
const STATUS_COLOR: Record<string, string> = {
  running: '#2f6bff',
  pending: '#ffb020',
  completed: '#16c784',
  failed: '#ff5c7a',
  cancelled: '#647189',
  active: '#2f6bff',
  maintenance: '#ffb020',
  info: '#2f6bff',
  warning: '#ffb020',
  error: '#ff5c7a',
  critical: '#ff5c7a',
}

const jobStatusData = computed(() => {
  const groups: Record<string, number> = {}
  jobsData.value.forEach((j) => {
    const key = j.status ?? 'unknown'
    groups[key] = (groups[key] ?? 0) + 1
  })
  return Object.entries(groups).map(([status, value]) => ({
    value,
    name: STATUS_TEXT[status] ?? status,
    itemStyle: { color: STATUS_COLOR[status] ?? '#647189' },
  }))
})

const gpuVendorData = computed(() => {
  const groups: Record<string, number> = {}
  gpuDevices.value.forEach((d) => {
    const key = (d.vendor ?? 'unknown') as GPUVendor | 'unknown'
    groups[key] = (groups[key] ?? 0) + 1
  })
  return Object.entries(groups).map(([vendor, value]) => ({
    value,
    name: VENDOR_LABEL[vendor] ?? vendor,
    itemStyle: { color: VENDOR_COLOR[vendor] ?? '#647189' },
  }))
})

function pieOption(data: unknown[], tooltipFmt: string) {
  return {
    tooltip: { trigger: 'item' as const, formatter: tooltipFmt },
    legend: { bottom: 0, itemWidth: 10, itemHeight: 10, textStyle: { color: '#647189', fontSize: 12 } },
    series: [
      {
        type: 'pie' as const,
        radius: ['52%', '74%'],
        center: ['50%', '44%'],
        avoidLabelOverlap: true,
        itemStyle: { borderRadius: 8, borderColor: '#fff', borderWidth: 2 },
        label: { show: true, color: '#647189', fontSize: 12, formatter: '{d}%' },
        data,
      },
    ],
  }
}

const resourceOption = computed(() =>
  pieOption(
    [
      { value: gpuUsed.value, name: '已使用', itemStyle: { color: '#2f6bff' } },
      { value: Math.max(gpuTotal.value - gpuUsed.value, 0), name: '可分配', itemStyle: { color: '#e4eaf3' } },
    ],
    '{b}: {c} ({d}%)',
  ),
)
const jobOption = computed(() => pieOption(jobStatusData.value, '{b}: {c} ({d}%)'))
const vendorOption = computed(() => pieOption(gpuVendorData.value, '{b}: {c} 张 ({d}%)'))

const resourceChartRef = ref<HTMLElement>()
const jobChartRef = ref<HTMLElement>()
const vendorChartRef = ref<HTMLElement>()
let resourceChart: echarts.ECharts | null = null
let jobChart: echarts.ECharts | null = null
let vendorChart: echarts.ECharts | null = null

function resizeCharts() {
  resourceChart?.resize()
  jobChart?.resize()
  vendorChart?.resize()
}

onMounted(() => {
  if (resourceChartRef.value) {
    resourceChart = echarts.init(resourceChartRef.value)
    resourceChart.setOption(resourceOption.value)
  }
  if (jobChartRef.value && jobStatusData.value.length > 0) {
    jobChart = echarts.init(jobChartRef.value)
    jobChart.setOption(jobOption.value)
  }
  if (vendorChartRef.value && gpuVendorData.value.length > 0) {
    vendorChart = echarts.init(vendorChartRef.value)
    vendorChart.setOption(vendorOption.value)
  }
  window.addEventListener('resize', resizeCharts)
})

onBeforeUnmount(() => {
  window.removeEventListener('resize', resizeCharts)
  resourceChart?.dispose()
  jobChart?.dispose()
  vendorChart?.dispose()
})

watch(resourceOption, (opt) => {
  if (resourceChart) resourceChart.setOption(opt, true)
  else if (resourceChartRef.value && !resourceChart) {
    resourceChart = echarts.init(resourceChartRef.value)
    resourceChart.setOption(opt)
  }
})
watch(jobOption, (opt) => {
  if (jobChart) jobChart.setOption(opt, true)
  else if (jobChartRef.value && jobStatusData.value.length > 0) {
    jobChart = echarts.init(jobChartRef.value)
    jobChart.setOption(opt)
  }
})
watch(vendorOption, (opt) => {
  if (vendorChart) vendorChart.setOption(opt, true)
  else if (vendorChartRef.value && gpuVendorData.value.length > 0) {
    vendorChart = echarts.init(vendorChartRef.value)
    vendorChart.setOption(opt)
  }
})

// ---------- 告警 ----------
const topAlerts = computed(() => alertsData.value.slice(0, 6))
function alertText(level?: string) {
  return STATUS_TEXT[level ?? 'info'] ?? level ?? '信息'
}
function alertColor(level?: string) {
  return STATUS_COLOR[level ?? 'info'] ?? '#647189'
}
function alertLevelClass(level?: string) {
  if (level === 'critical' || level === 'error') return 'failed'
  if (level === 'warning') return 'pending'
  return 'running'
}
</script>

<style scoped>
.kpi-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(210px, 1fr));
  gap: var(--mc-gap);
}
.kpi-card {
  background: var(--mc-surface);
  border-radius: var(--mc-radius-lg);
  box-shadow: var(--mc-shadow-raised-sm);
  padding: 20px;
  display: flex;
  align-items: center;
  gap: 14px;
}
.kpi-icon {
  width: 44px;
  height: 44px;
  border-radius: var(--mc-radius-md);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.kpi-body { flex: 1; min-width: 0; }
.kpi-title { font-size: 13px; color: var(--mc-text-3); margin-bottom: 2px; }
.kpi-value { font-size: 26px; font-weight: 680; letter-spacing: -0.5px; color: var(--mc-text-1); }
.kpi-suffix { font-size: 14px; font-weight: 400; color: var(--mc-text-3); }
.kpi-footer { font-size: 12.5px; color: var(--mc-text-3); margin-top: 4px; }

.chart-box { height: 280px; }
.chart-card-head { display: flex; justify-content: space-between; align-items: center; }
.chart-card-extra { font-size: 12px; color: var(--mc-text-3); font-weight: 400; }

.alert-list { list-style: none; margin: 0; padding: 0; }
.alert-item { padding: 12px 0; border-bottom: 1px solid var(--mc-line); }
.alert-item:last-child { border-bottom: none; }
.alert-line { display: flex; align-items: center; gap: 10px; margin-bottom: 4px; }
.alert-message { font-size: 14px; color: var(--mc-text-1); }
.alert-detail { font-size: 12.5px; color: var(--mc-text-3); padding-left: 62px; }
</style>

// metaclouds-frontend/src/pages/Dashboard.tsx
﻿import React, { useCallback, useEffect, useMemo, useState } from 'react';
import {
  Card,
  Statistic,
  Progress,
  List,
  Button,
  Space,
  Segmented,
  Skeleton,
  Tooltip,
  Tag,
} from 'antd';
import ResponsiveChart from '../components/ResponsiveChart';
import {
  DatabaseOutlined,
  CloudOutlined,
  ClockCircleOutlined,
  BellOutlined,
  ReloadOutlined,
  AppstoreOutlined,
  ApiOutlined,
  TeamOutlined,
} from '@ant-design/icons';
import {
  useGetClustersQuery,
  useGetResourcesQuery,
  useGetJobsQuery,
  useGetAlertsQuery,
  useGetGPUDevicesQuery,
  useGetPartitionsQuery,
  useGetSchedulerIntegrationsQuery,
  useGetTenantsQuery,
} from '../store/api';
import { extractArrayData } from '../utils/api';
import { ErrorState, EmptyState } from '../components/States';
import DraggableGrid, { type GridItem } from '../components/DraggableGrid';
import { useThemeMode } from '../theme/ThemeModeContext';
import { chartPalette, getNeutral, statusColor, statusText } from '../theme/tokens';
import type { GPUVendor } from '../types';

const STORAGE_KEY = 'mc-dashboard-layout-v1';

const DEFAULT_ORDER = [
  'kpi-cluster',
  'kpi-util',
  'kpi-running',
  'kpi-alerts',
  'kpi-tenants',
  'chart-resource',
  'chart-job',
  'chart-gpu-vendor',
  'kpi-partition',
  'kpi-scheduler',
  'alerts',
];

interface Layout {
  order: string[];
  hidden: string[];
}

const readLayout = (): Layout => {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return { order: DEFAULT_ORDER, hidden: [] };
    const parsed = JSON.parse(raw) as Partial<Layout>;
    const savedOrder = Array.isArray(parsed.order) ? parsed.order : [];
    // 过滤已不存在的卡片，并补齐新增卡片，保证向前兼容
    const order = [
      ...savedOrder.filter((id) => DEFAULT_ORDER.includes(id)),
      ...DEFAULT_ORDER.filter((id) => !savedOrder.includes(id)),
    ];
    const hidden = Array.isArray(parsed.hidden)
      ? parsed.hidden.filter((id) => DEFAULT_ORDER.includes(id))
      : [];
    return { order, hidden };
  } catch {
    return { order: DEFAULT_ORDER, hidden: [] };
  }
};

const VENDOR_LABEL: Record<GPUVendor, string> = {
  nvidia: 'NVIDIA',
  enflame: '燧原',
  moore_threads: '摩尔线程',
  domestic_x: '国产X',
};

const VENDOR_COLOR: Record<GPUVendor, string> = {
  nvidia: '#76b900',
  enflame: '#2f6bff',
  moore_threads: '#7c5cff',
  domestic_x: '#fa8c16',
};

const Dashboard: React.FC = () => {
  const { mode } = useThemeMode();
  const colors = useMemo(() => getNeutral(mode), [mode]);

  const { data: clusters, isLoading: clustersLoading, error: clustersError, refetch: refetchClusters } =
    useGetClustersQuery(undefined);
  const { data: resources, isLoading: resourcesLoading, error: resourcesError, refetch: refetchResources } =
    useGetResourcesQuery(undefined);
  const { data: jobs, isLoading: jobsLoading, error: jobsError, refetch: refetchJobs } =
    useGetJobsQuery(undefined);
  const { data: alerts, isLoading: alertsLoading, error: alertsError, refetch: refetchAlerts } =
    useGetAlertsQuery(undefined);
  const { data: gpuDevices } = useGetGPUDevicesQuery({});
  const { data: partitions } = useGetPartitionsQuery({});
  const { data: schedulers } = useGetSchedulerIntegrationsQuery();
  const { data: tenants } = useGetTenantsQuery(undefined);

  const clustersData = extractArrayData(clusters);
  const resourcesData = extractArrayData(resources);
  const jobsData = extractArrayData(jobs);
  const alertsData = extractArrayData(alerts);
  const gpuDevicesData = gpuDevices ?? [];
  const partitionsData = partitions ?? [];
  const schedulersData = schedulers ?? [];
  const tenantsData = extractArrayData(tenants);

  const [layout, setLayout] = useState<Layout>(readLayout);
  const [editable, setEditable] = useState(false);
  const [range, setRange] = useState('近 7 天');

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(layout));
    } catch {
      /* 忽略写入失败 */
    }
  }, [layout]);

  // 真实指标：GPU 利用率取自资源 used/total，而非硬编码
  const gpuUsed = useMemo(
    () => resourcesData.reduce((s: number, r: { used?: number }) => s + (Number(r.used) || 0), 0),
    [resourcesData],
  );
  const gpuTotal = useMemo(
    () => resourcesData.reduce((s: number, r: { total?: number }) => s + (Number(r.total) || 0), 0),
    [resourcesData],
  );
  const utilization = gpuTotal > 0 ? Math.round((gpuUsed / gpuTotal) * 100) : 0;

  const clusterCount = clustersData.length;
  const runningJobs = jobsData.filter((j: { status: string }) => j.status === 'running').length;
  const pendingJobs = jobsData.filter((j: { status: string }) => j.status === 'pending').length;
  const totalJobs = jobsData.length;
  const alertCount = alertsData.length;

  // 分区统计
  const partitionStats = useMemo(() => ({
    total: partitionsData.length,
    active: partitionsData.filter((p) => p.status === 'active').length,
    maintenance: partitionsData.filter((p) => p.status === 'maintenance').length,
  }), [partitionsData]);

  // 调度器统计
  const schedulerStats = useMemo(() => ({
    total: schedulersData.length,
    active: schedulersData.filter((s) => s.status === 'active').length,
    error: schedulersData.filter((s) => s.status === 'error').length,
  }), [schedulersData]);

  // GPU 厂商分布
  const gpuVendorData = useMemo(() => {
    const groups: Record<string, number> = {};
    gpuDevicesData.forEach((d) => {
      const key = d.vendor ?? 'unknown';
      groups[key] = (groups[key] ?? 0) + 1;
    });
    return Object.entries(groups).map(([vendor, value]) => ({
      value,
      name: VENDOR_LABEL[vendor as GPUVendor] ?? vendor,
      itemStyle: { color: VENDOR_COLOR[vendor as GPUVendor] ?? colors.text3 },
    }));
  }, [gpuDevicesData, colors.text3]);

  const hasError = clustersError || resourcesError || jobsError || alertsError;
  const isLoading = clustersLoading || resourcesLoading || jobsLoading || alertsLoading;

  const refetchAll = useCallback(() => {
    refetchClusters();
    refetchResources();
    refetchJobs();
    refetchAlerts();
  }, [refetchClusters, refetchResources, refetchJobs, refetchAlerts]);

  const jobStatusData = useMemo(() => {
    const groups: Record<string, number> = {};
    jobsData.forEach((j: { status?: string }) => {
      const key = j.status ?? 'unknown';
      groups[key] = (groups[key] ?? 0) + 1;
    });
    return Object.entries(groups).map(([status, value]) => ({
      value,
      name: statusText[status] ?? status,
      itemStyle: { color: statusColor[status] ?? colors.text3 },
    }));
  }, [jobsData, colors.text3]);

  const resourceOption = useMemo(
    () => ({
      tooltip: { trigger: 'item' as const, formatter: '{b}: {c} ({d}%)' },
      legend: {
        bottom: 0,
        itemWidth: 10,
        itemHeight: 10,
        textStyle: { color: colors.text3, fontSize: 12 },
      },
      series: [
        {
          type: 'pie' as const,
          radius: ['52%', '74%'],
          center: ['50%', '44%'],
          avoidLabelOverlap: true,
          itemStyle: { borderRadius: 8, borderColor: colors.surface, borderWidth: 2 },
          label: { show: true, color: colors.text3, fontSize: 12, formatter: '{d}%' },
          data: [
            { value: gpuUsed, name: '已使用', itemStyle: { color: chartPalette.gpu } },
            {
              value: Math.max(gpuTotal - gpuUsed, 0),
              name: '可分配',
              itemStyle: { color: colors.line },
            },
          ],
        },
      ],
    }),
    [gpuUsed, gpuTotal, colors],
  );

  const jobOption = useMemo(
    () => ({
      tooltip: { trigger: 'item' as const, formatter: '{b}: {c} ({d}%)' },
      legend: {
        bottom: 0,
        itemWidth: 10,
        itemHeight: 10,
        textStyle: { color: colors.text3, fontSize: 12 },
      },
      series: [
        {
          type: 'pie' as const,
          radius: ['52%', '74%'],
          center: ['50%', '44%'],
          avoidLabelOverlap: true,
          itemStyle: { borderRadius: 8, borderColor: colors.surface, borderWidth: 2 },
          label: { show: true, color: colors.text3, fontSize: 12, formatter: '{d}%' },
          data: jobStatusData,
        },
      ],
    }),
    [jobStatusData, colors],
  );

  // GPU 厂商分布饼图 option
  const gpuVendorOption = useMemo(
    () => ({
      tooltip: { trigger: 'item' as const, formatter: '{b}: {c} 张 ({d}%)' },
      legend: {
        bottom: 0,
        itemWidth: 10,
        itemHeight: 10,
        textStyle: { color: colors.text3, fontSize: 12 },
      },
      series: [
        {
          type: 'pie' as const,
          radius: ['52%', '74%'],
          center: ['50%', '44%'],
          avoidLabelOverlap: true,
          itemStyle: { borderRadius: 8, borderColor: colors.surface, borderWidth: 2 },
          label: { show: true, color: colors.text3, fontSize: 12, formatter: '{d}%' },
          data: gpuVendorData,
        },
      ],
    }),
    [gpuVendorData, colors],
  );

  const handleReorder = (ids: string[]) => setLayout((prev) => ({ ...prev, order: ids }));

  const handleMove = (id: string, dir: -1 | 1) =>
    setLayout((prev) => {
      const order = [...prev.order];
      const from = order.indexOf(id);
      const to = from + dir;
      if (from < 0 || to < 0 || to >= order.length) return prev;
      [order[from], order[to]] = [order[to], order[from]];
      return { ...prev, order };
    });

  const handleToggleHidden = (id: string) =>
    setLayout((prev) => ({
      ...prev,
      hidden: prev.hidden.includes(id)
        ? prev.hidden.filter((h) => h !== id)
        : [...prev.hidden, id],
    }));

  const handleReset = () => {
    setLayout({ order: DEFAULT_ORDER, hidden: [] });
    try {
      localStorage.removeItem(STORAGE_KEY);
    } catch {
      /* 忽略 */
    }
  };

  /**
   * 统一的 KPI 卡。
   * 注意：antd Statistic 的 value 仅接受 string | number（传入 ReactNode 会被字符串化），
   * 因此单位一律通过 suffix 传入。
   */
  const statCard = (
    icon: React.ReactNode,
    bg: string,
    title: string,
    value: string | number,
    suffix: React.ReactNode,
    footer: React.ReactNode,
  ) => (
    <Card styles={{ body: { padding: 20 } }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        <div
          style={{
            width: 44,
            height: 44,
            borderRadius: 'var(--mc-radius-lg)',
            background: bg,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: '#fff',
            fontSize: 20,
            flexShrink: 0,
          }}
        >
          {icon}
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <Statistic
            className="mc-num"
            title={title}
            value={value}
            suffix={suffix}
            valueStyle={{ fontSize: 'var(--mc-fs-metric)', fontWeight: 680, letterSpacing: '-0.5px' }}
          />
          <div style={{ marginTop: 4, minHeight: 20 }}>{footer}</div>
        </div>
      </div>
    </Card>
  );

  const cards: GridItem[] = [
    {
      id: 'kpi-cluster',
      span: { xs: 12, sm: 12, md: 6, lg: 6, xl: 3, '2xl': 3 },
      title: '集群数量',
      node: statCard(
        <DatabaseOutlined />,
        'linear-gradient(135deg, #1677ff, #4096ff)',
        '集群数量',
        clusterCount,
        <span style={{ fontSize: 14, fontWeight: 400, color: 'var(--mc-text-3)' }}> 个</span>,
        <span style={{ fontSize: 12.5, color: 'var(--mc-text-3)' }}>统一纳管的计算集群</span>,
      ),
    },
    {
      id: 'kpi-util',
      span: { xs: 12, sm: 12, md: 6, lg: 6, xl: 3, '2xl': 3 },
      title: 'GPU 利用率',
      node: statCard(
        <CloudOutlined />,
        'linear-gradient(135deg, #0958d9, #1677ff)',
        'GPU 利用率',
        utilization,
        '%',
        <Progress
          percent={utilization}
          size="small"
          status={utilization > 80 ? 'exception' : 'normal'}
          strokeColor={utilization > 80 ? statusColor.failed : '#1677ff'}
          showInfo={false}
        />,
      ),
    },
    {
      id: 'kpi-running',
      span: { xs: 12, sm: 12, md: 6, lg: 6, xl: 3, '2xl': 3 },
      title: '运行中作业',
      node: statCard(
        <ClockCircleOutlined />,
        'linear-gradient(135deg, #4096ff, #69b1ff)',
        '运行中作业',
        runningJobs,
        <span style={{ fontSize: 14, fontWeight: 400, color: 'var(--mc-text-3)' }}>
          {' '}
          / {totalJobs}
        </span>,
        <span style={{ fontSize: 12.5, color: 'var(--mc-text-3)' }}>
          排队中 <b className="mc-num">{pendingJobs}</b> 个
        </span>,
      ),
    },
    {
      id: 'kpi-alerts',
      span: { xs: 12, sm: 12, md: 6, lg: 6, xl: 3, '2xl': 3 },
      title: '活跃告警',
      node: statCard(
        <BellOutlined />,
        alertCount > 0
          ? 'linear-gradient(135deg, #ff4d4f, #ff7875)'
          : 'linear-gradient(135deg, #1677ff, #4096ff)',
        '活跃告警',
        alertCount,
        ' 条',
        <span
          style={{
            fontSize: 12.5,
            color: alertCount > 0 ? 'var(--mc-danger)' : '#1677ff',
          }}
        >
          {alertCount > 0 ? '需要关注' : '运行正常'}
        </span>,
      ),
    },
    {
      id: 'kpi-tenants',
      span: { xs: 12, sm: 12, md: 6, lg: 6, xl: 3, '2xl': 3 },
      title: '租户数量',
      node: statCard(
        <TeamOutlined />,
        'linear-gradient(135deg, #1677ff, #4096ff)',
        '租户数量',
        tenantsData.length,
        <span style={{ fontSize: 14, fontWeight: 400, color: 'var(--mc-text-3)' }}> 个</span>,
        <span style={{ fontSize: 12.5, color: 'var(--mc-text-3)' }}>多租户资源隔离与配额</span>,
      ),
    },
    {
      id: 'chart-resource',
      span: { xs: 12, sm: 12, md: 12, lg: 6, xl: 6, '2xl': 6 },
      title: '资源分布',
      node: (
        <Card title="资源分布" extra={<span style={{ fontSize: 12, color: 'var(--mc-text-3)' }}>GPU 卡</span>}>
          {gpuTotal > 0 ? (
            <ResponsiveChart option={resourceOption} size="md" />
          ) : (
            <EmptyState
              title="暂无资源数据"
              description="接入 GPU 资源后，这里会展示已使用与可分配的占比。"
            />
          )}
        </Card>
      ),
    },
    {
      id: 'chart-job',
      span: { xs: 12, sm: 12, md: 12, lg: 6, xl: 6, '2xl': 6 },
      title: '作业状态分布',
      node: (
        <Card title="作业状态分布" extra={<span style={{ fontSize: 12, color: 'var(--mc-text-3)' }}>共 {totalJobs} 个</span>}>
          {jobStatusData.length > 0 ? (
            <ResponsiveChart option={jobOption} size="md" />
          ) : (
            <EmptyState
              title="还没有作业"
              description="提交第一个作业后，这里会按状态展示分布。"
            />
          )}
        </Card>
      ),
    },
    {
      id: 'chart-gpu-vendor',
      span: { xs: 12, sm: 12, md: 12, lg: 6, xl: 6, '2xl': 6 },
      title: 'GPU 厂商分布',
      node: (
        <Card title="GPU 厂商分布" extra={<span style={{ fontSize: 12, color: 'var(--mc-text-3)' }}>共 {gpuDevicesData.length} 张</span>}>
          {gpuVendorData.length > 0 ? (
            <ResponsiveChart option={gpuVendorOption} size="md" />
          ) : (
            <EmptyState
              title="暂无 GPU 设备"
              description="登记 GPU 设备后，这里会按厂商展示分布。"
            />
          )}
        </Card>
      ),
    },
    {
      id: 'kpi-partition',
      span: { xs: 12, sm: 12, md: 6, lg: 6, xl: 3, '2xl': 3 },
      title: '分区状态',
      node: statCard(
        <AppstoreOutlined />,
        'linear-gradient(135deg, #1677ff, #4096ff)',
        '分区总数',
        partitionStats.total,
        <span style={{ fontSize: 14, fontWeight: 400, color: 'var(--mc-text-3)' }}> 个</span>,
        <Space size={8}>
          <Tag color="blue">活跃 {partitionStats.active}</Tag>
          <Tag color="orange">维护 {partitionStats.maintenance}</Tag>
        </Space>,
      ),
    },
    {
      id: 'kpi-scheduler',
      span: { xs: 12, sm: 12, md: 6, lg: 6, xl: 3, '2xl': 3 },
      title: '调度器集成',
      node: statCard(
        <ApiOutlined />,
        'linear-gradient(135deg, #0958d9, #1677ff)',
        '调度器总数',
        schedulerStats.total,
        <span style={{ fontSize: 14, fontWeight: 400, color: 'var(--mc-text-3)' }}> 个</span>,
        <Space size={8}>
          <Tag color="blue">活跃 {schedulerStats.active}</Tag>
          {schedulerStats.error > 0 && <Tag color="red">异常 {schedulerStats.error}</Tag>}
        </Space>,
      ),
    },
    {
      id: 'alerts',
      span: { xs: 12, sm: 12, md: 12, lg: 12, xl: 12, '2xl': 12 },
      title: '最近告警',
      node: (
        <Card title="最近告警" extra={<span style={{ fontSize: 12, color: 'var(--mc-text-3)' }}>按严重程度排序</span>}>
          {alertsData.length > 0 ? (
            <List
              dataSource={alertsData.slice(0, 6)}
              renderItem={(item: Record<string, unknown>) => {
                const level = String(item.level ?? 'info');
                const color = statusColor[level] ?? colors.text3;
                return (
                  <List.Item style={{ padding: '12px 0' }}>
                    <div style={{ width: '100%' }}>
                      <div style={{ marginBottom: 4 }}>
                        <Space>
                          <span className={`mc-status ${level === 'critical' ? 'failed' : 'pending'}`}>
                            <i className="mc-status-dot" style={{ background: color }} />
                            {statusText[level] ?? level}
                          </span>
                          <span>{String(item.message ?? item.title ?? '未知告警')}</span>
                        </Space>
                      </div>
                      <div style={{ fontSize: 12.5, color: 'var(--mc-text-3)' }}>
                        {String(item.details ?? item.description ?? '暂无详情')}
                      </div>
                    </div>
                  </List.Item>
                );
              }}
            />
          ) : (
            <EmptyState title="暂无告警" description="系统运行正常，有新的告警会第一时间出现在这里。" />
          )}
        </Card>
      ),
    },
  ];

  // 编辑模式下渲染全部卡片（含已隐藏），便于重新显示与调整顺序
  const orderedCards = useMemo(() => {
    const map = new Map(cards.map((c) => [c.id, c]));
    const ordered = layout.order
      .map((id) => map.get(id))
      .filter((c): c is GridItem => Boolean(c));
    return editable ? ordered : ordered.filter((c) => !layout.hidden.includes(c.id));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [layout, editable, clusterCount, utilization, runningJobs, alertCount, totalJobs, pendingJobs, gpuUsed, gpuTotal, jobStatusData, resourceOption, jobOption, gpuVendorOption, alertsData, partitionStats, schedulerStats, gpuDevicesData.length]);

  const skeletonCards = (
    <div className="dg">
      {[0, 1, 2, 3].map((i) => (
        <div key={i} className="dg-item dg-span-xs-12 dg-span-md-6 dg-span-xl-3">
          <Card>
            <Skeleton active paragraph={{ rows: 2 }} />
          </Card>
        </div>
      ))}
      <div className="dg-item dg-span-xs-12 dg-span-lg-6">
        <Card>
          <Skeleton active paragraph={{ rows: 7 }} />
        </Card>
      </div>
      <div className="dg-item dg-span-xs-12">
        <Card>
          <Skeleton active paragraph={{ rows: 4 }} />
        </Card>
      </div>
    </div>
  );

  return (
    <div className="mc-page">
      <div className="mc-page-head">
        <div className="mc-page-head-main">
          <h1 className="mc-page-title">算力总览</h1>
          <p className="mc-page-desc">
            {range} · 实时掌握全平台算力水位、作业吞吐与风险告警
          </p>
        </div>
        <div className="mc-page-head-extra">
          <Segmented
            value={range}
            onChange={(v) => setRange(String(v))}
            options={['今日', '近 7 天', '近 30 天']}
          />
          <Tooltip title="刷新数据">
            <Button icon={<ReloadOutlined />} onClick={refetchAll}>
              刷新
            </Button>
          </Tooltip>
          <Button type={editable ? 'primary' : 'default'} onClick={() => setEditable((v) => !v)}>
            {editable ? '完成布局' : '自定义布局'}
          </Button>
          {editable && <Button onClick={handleReset}>恢复默认</Button>}
        </div>
      </div>

      {hasError ? (
        <ErrorState
          title="仪表盘数据加载失败"
          description="部分接口请求失败，可尝试重新加载；若持续失败请联系平台管理员。"
          onRetry={refetchAll}
        />
      ) : isLoading ? (
        skeletonCards
      ) : (
        <DraggableGrid
          items={orderedCards}
          editable={editable}
          hiddenIds={layout.hidden}
          onReorder={handleReorder}
          onMove={handleMove}
          onToggleHidden={handleToggleHidden}
        />
      )}
    </div>
  );
};

export default Dashboard;
