// metaclouds-frontend-vue/src/pages/GPUManagement.vue
<template>
  <div class="mc-page">
    <div class="mc-page-head">
      <div class="mc-page-head-main">
        <h1 class="mc-page-title">GPU 细粒度管理</h1>
        <p class="mc-page-desc">
          共 {{ stats.total }} 张 GPU · 已分配 {{ stats.allocated }} · 可用 {{ stats.available }} · 维护中 {{ stats.maintenance }} · 故障 {{ stats.fault }}
        </p>
      </div>
      <div class="mc-page-head-extra">
        <Can :roles="['admin', 'manager']">
          <el-button type="primary" @click="openCreate">新增 GPU 设备</el-button>
        </Can>
      </div>
    </div>

    <!-- GPU 概览卡片 -->
    <el-row :gutter="16" class="mc-mb">
      <el-col :xs="12" :sm="12" :md="8" :lg="4" :xl="4">
        <el-card shadow="never">
          <div class="stat-label">总设备数</div>
          <div class="stat-value">{{ stats.total }} <span class="stat-unit">张</span></div>
        </el-card>
      </el-col>
      <el-col :xs="12" :sm="12" :md="8" :lg="4" :xl="4">
        <el-card shadow="never">
          <div class="stat-label">可用</div>
          <div class="stat-value" style="color: var(--mc-success)">{{ stats.available }} <span class="stat-unit">张</span></div>
        </el-card>
      </el-col>
      <el-col :xs="12" :sm="12" :md="8" :lg="4" :xl="4">
        <el-card shadow="never">
          <div class="stat-label">已分配</div>
          <div class="stat-value" style="color: var(--mc-warning)">{{ stats.allocated }} <span class="stat-unit">张</span></div>
        </el-card>
      </el-col>
      <el-col :xs="12" :sm="12" :md="8" :lg="4" :xl="4">
        <el-card shadow="never">
          <div class="stat-label">维护中</div>
          <div class="stat-value" style="color: var(--mc-brand-fg)">{{ stats.maintenance }} <span class="stat-unit">张</span></div>
        </el-card>
      </el-col>
      <el-col :xs="12" :sm="12" :md="8" :lg="4" :xl="4">
        <el-card shadow="never">
          <div class="stat-label">故障</div>
          <div class="stat-value" style="color: var(--mc-danger)">{{ stats.fault }} <span class="stat-unit">张</span></div>
        </el-card>
      </el-col>
      <el-col :xs="24" :sm="24" :md="24" :lg="4" :xl="4">
        <el-card shadow="never">
          <div class="stat-label">按厂商分布</div>
          <div class="vendor-dist">
            <el-tag v-for="(count, vendor) in vendorDist" :key="vendor" :type="vendorTagType(vendor as GPUVendor)" size="small">
              {{ vendorLabel(vendor as GPUVendor) }} {{ count }}
            </el-tag>
            <span v-if="!Object.keys(vendorDist).length" class="mc-empty-mini">-</span>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <!-- 容器虚拟化隔离能力 + 隔离引擎 + 分配粒度（skill.md 4.2） -->
    <el-card shadow="never" class="mc-mb" header="容器虚拟化隔离与分配能力">
      <el-row :gutter="16">
        <el-col :span="6" v-for="c in ISOLATION_CAPS" :key="c.name">
          <div class="iso-cap">
            <div class="iso-cap-name">{{ c.name }}</div>
            <div class="iso-cap-desc">{{ c.desc }}</div>
          </div>
        </el-col>
      </el-row>
      <el-row :gutter="16" class="mc-mt">
        <el-col :span="12">
          <el-card shadow="never" class="iso-sub" header="隔离引擎">
            <el-tag type="primary" size="small" class="mc-mr">用户态虚拟化隔离引擎（轻量高性能）</el-tag>
            <el-tag type="warning" size="small">内核态虚拟化隔离引擎（安全底层隔离）</el-tag>
          </el-card>
        </el-col>
        <el-col :span="12">
          <el-card shadow="never" class="iso-sub" header="GPU 分配粒度分布">
            <el-tag type="success" size="small" class="mc-mr">1 GPU × {{ fracFull }}</el-tag>
            <el-tag type="primary" size="small" class="mc-mr">1/2 GPU × {{ fracHalf }}</el-tag>
            <el-tag type="warning" size="small" class="mc-mr">1/4 GPU × {{ fracQuarter }}</el-tag>
            <el-tag size="small">N GPU 多卡并行</el-tag>
          </el-card>
        </el-col>
      </el-row>
    </el-card>

    <!-- 筛选器 -->
    <el-card shadow="never" class="mc-mb">
      <div class="toolbar">
        <el-input
          v-model="keyword"
          placeholder="搜索节点名 / 型号"
          clearable
          style="width: 240px"
          aria-label="搜索 GPU 节点"
        />
        <el-select v-model="vendorFilter" placeholder="厂商筛选" clearable style="width: 160px">
          <el-option v-for="o in VENDOR_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
        </el-select>
        <el-select v-model="statusFilter" placeholder="状态筛选" clearable style="width: 150px">
          <el-option v-for="o in GPU_STATUS_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
        </el-select>
        <el-select v-model="clusterFilter" placeholder="集群筛选" clearable style="width: 180px">
          <el-option v-for="c in clustersData" :key="c.id" :label="c.name" :value="c.id" />
        </el-select>
      </div>
    </el-card>

    <!-- 设备表格 -->
    <el-card shadow="never" id="gpu-table">
      <PageState
        :loading="devices.loading.value"
        :error="devices.error.value"
        :data="pagedData"
        empty-text="暂无 GPU 设备，登记后可进行细粒度分配与监控"
        @retry="devices.refetch"
      >
        <el-table :data="pagedData" stripe border style="width: 100%">
          <el-table-column prop="id" label="ID" width="70">
            <template #default="{ row }"><span class="mc-mono">{{ row.id }}</span></template>
          </el-table-column>
          <el-table-column label="节点名" width="150">
            <template #default="{ row }">
              <el-button link type="primary" @click="detailDevice = row">{{ row.node_name }}</el-button>
            </template>
          </el-table-column>
          <el-table-column label="厂商" width="110">
            <template #default="{ row }">
              <el-tag :type="vendorTagType(row.vendor)" size="small">{{ vendorLabel(row.vendor) }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="model" label="型号" width="110" />
          <el-table-column label="索引" width="80">
            <template #default="{ row }"><span class="mc-num">{{ row.index ?? '-' }}</span></template>
          </el-table-column>
          <el-table-column label="总显存(GB)" width="110">
            <template #default="{ row }"><span class="mc-num">{{ row.total_memory_gb ?? '-' }}</span></template>
          </el-table-column>
          <el-table-column label="已用显存(GB)" width="120">
            <template #default="{ row }"><span class="mc-num">{{ row.used_memory_gb ?? '-' }}</span></template>
          </el-table-column>
          <el-table-column label="MIG" width="80">
            <template #default="{ row }">
              <el-tag :type="row.mig_enabled ? 'primary' : 'info'" size="small">{{ row.mig_enabled ? '开启' : '关闭' }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="driver_version" label="驱动版本" width="110" />
          <el-table-column prop="cuda_version" label="CUDA版本" width="100" />
          <el-table-column label="状态" width="100">
            <template #default="{ row }">
              <el-tag :type="statusType(row.status)" size="small">{{ statusText(row.status) }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column label="利用率" width="140">
            <template #default="{ row }">
              <el-progress :percentage="row.utilization ?? 0" :stroke-width="8" />
            </template>
          </el-table-column>
          <el-table-column label="温度(°C)" width="90">
            <template #default="{ row }"><span class="mc-num">{{ row.temperature ?? '-' }}</span></template>
          </el-table-column>
          <el-table-column label="功耗(W)" width="90">
            <template #default="{ row }"><span class="mc-num">{{ row.power_draw ?? '-' }}</span></template>
          </el-table-column>
          <el-table-column label="操作" width="240" fixed="right">
            <template #default="{ row }">
              <Can :roles="['admin', 'manager']">
                <el-button v-if="row.status === 'available'" link type="primary" size="small" @click="openAllocate(row)">分配</el-button>
              </Can>
              <Can :roles="['admin', 'manager']">
                <el-button link type="primary" size="small" @click="openEdit(row)">编辑</el-button>
              </Can>
              <Can :roles="['admin', 'manager']">
                <el-button v-if="row.status !== 'maintenance'" link type="warning" size="small" @click="handleSetMaintenance(row)">维护</el-button>
              </Can>
              <Can :roles="['admin', 'manager']">
                <el-button link type="primary" size="small" @click="openAllocations(row)">分配记录</el-button>
              </Can>
              <Can :roles="['admin', 'manager']">
                <el-popconfirm title="删除该 GPU 设备？设备记录将被移除且不可恢复。" confirm-button-text="确认删除" cancel-button-text="返回" @confirm="handleDelete(row.id)">
                  <template #reference>
                    <el-button link type="danger" size="small">删除</el-button>
                  </template>
                </el-popconfirm>
              </Can>
            </template>
          </el-table-column>
        </el-table>
        <el-pagination
          v-model:current-page="currentPage"
          background
          layout="prev, pager, next, total"
          :total="searchedDevices.length"
          :page-size="pageSize"
          style="margin-top: 12px; justify-content: flex-end"
        />
      </PageState>
    </el-card>

    <!-- 新建/编辑 Dialog -->
    <el-dialog
      v-model="dialogVisible"
      :title="editingDevice ? '编辑 GPU 设备' : '新增 GPU 设备'"
      width="720px"
      destroy-on-close
    >
      <el-form ref="formRef" :model="form" :rules="rules" label-position="top">
        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="节点名" prop="node_name">
              <el-input v-model="form.node_name" placeholder="例如：gpu-node-01" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="厂商" prop="vendor">
              <el-select v-model="form.vendor" placeholder="请选择厂商" style="width: 100%">
                <el-option v-for="o in VENDOR_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="型号" prop="model">
              <el-input v-model="form.model" placeholder="例如：A100-80GB" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="GPU 索引" prop="index">
              <el-input-number v-model="form.index" :min="0" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="总显存(GB)" prop="total_memory_gb">
              <el-input-number v-model="form.total_memory_gb" :min="0" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="可分配显存(GB)" prop="allocatable_memory_gb">
              <el-input-number v-model="form.allocatable_memory_gb" :min="0" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="驱动版本" prop="driver_version">
              <el-input v-model="form.driver_version" placeholder="例如：535.129.03" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="CUDA 版本" prop="cuda_version">
              <el-input v-model="form.cuda_version" placeholder="例如：12.2" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="所属集群" prop="cluster_id">
              <el-select v-model="form.cluster_id" placeholder="请选择集群" clearable style="width: 100%">
                <el-option v-for="c in clustersData" :key="c.id" :label="c.name" :value="c.id" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="状态" prop="status">
              <el-select v-model="form.status" placeholder="请选择状态" style="width: 100%">
                <el-option v-for="o in GPU_STATUS_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="MIG 开启" prop="mig_enabled">
              <el-switch v-model="form.mig_enabled" />
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="详情" prop="details">
              <el-input v-model="form.details" type="textarea" :rows="2" placeholder="选填" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <Can :roles="['admin', 'manager']">
          <el-button type="primary" @click="submitForm">{{ editingDevice ? '保存' : '创建' }}</el-button>
        </Can>
      </template>
    </el-dialog>

    <!-- 分配 GPU Dialog -->
    <el-dialog
      v-model="allocateVisible"
      :title="`分配 GPU — ${allocatingDevice?.node_name ?? ''} ${allocatingDevice?.model ?? ''}`"
      width="560px"
      destroy-on-close
    >
      <el-form ref="allocFormRef" :model="allocForm" label-position="top">
        <el-form-item label="GPU 分配粒度" prop="fraction" required>
          <el-select v-model="allocForm.fraction" placeholder="请选择分配粒度" style="width: 100%">
            <el-option label="1 GPU（整卡，计算密集型）" :value="1" />
            <el-option label="1/2 GPU（中等需求）" :value="0.5" />
            <el-option label="1/4 GPU（轻量任务）" :value="0.25" />
          </el-select>
        </el-form-item>
        <el-form-item label="分配显存(GB)">
          <el-input-number v-model="allocForm.memory_gb" :min="0" style="width: 100%" placeholder="留空则按粒度自动分配" />
        </el-form-item>
        <el-row :gutter="16">
          <el-col :span="8">
            <el-form-item label="作业ID">
              <el-input-number v-model="allocForm.job_id" :min="0" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="租户ID">
              <el-input-number v-model="allocForm.tenant_id" :min="0" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="用户ID">
              <el-input-number v-model="allocForm.user_id" :min="0" style="width: 100%" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <el-button @click="allocateVisible = false">取消</el-button>
        <Can :roles="['admin', 'manager']">
          <el-button type="primary" @click="submitAllocate">确认分配</el-button>
        </Can>
      </template>
    </el-dialog>

    <!-- GPU 分配记录 Drawer -->
    <el-drawer v-model="allocDrawerVisible" title="GPU 分配记录" size="720px">
      <el-alert v-if="currentAllocations.length === 0" type="info" :closable="false" title="暂无分配记录" />
      <el-table v-else :data="currentAllocations" size="small" stripe>
        <el-table-column prop="device_id" label="设备ID" width="90" />
        <el-table-column prop="job_id" label="作业ID" width="90" />
        <el-table-column label="分配粒度" width="110">
          <template #default="{ row }">
            <el-tag type="primary" size="small">
              {{ row.fraction >= 1 ? '1 GPU' : row.fraction === 0.5 ? '1/2 GPU' : row.fraction === 0.25 ? '1/4 GPU' : `${row.fraction} GPU` }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="显存(GB)" width="100">
          <template #default="{ row }"><span class="mc-num">{{ row.memory_gb ?? '-' }}</span></template>
        </el-table-column>
        <el-table-column prop="mig_profile" label="MIG Profile" width="130">
          <template #default="{ row }">{{ row.mig_profile ?? '-' }}</template>
        </el-table-column>
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="statusType(row.status)" size="small">{{ statusText(row.status) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="started_at" label="开始时间" width="170" />
        <el-table-column label="操作" width="90">
          <template #default="{ row }">
            <Can v-if="row.status === 'active'" :roles="['admin', 'manager']">
              <el-popconfirm title="释放该分配？" confirm-button-text="释放" cancel-button-text="取消" @confirm="releaseAllocation(row)">
                <template #reference>
                  <el-button link type="danger" size="small">释放</el-button>
                </template>
              </el-popconfirm>
            </Can>
            <span v-else>-</span>
          </template>
        </el-table-column>
      </el-table>
    </el-drawer>

    <!-- 设备详情 Drawer -->
    <el-drawer v-model="detailVisible" title="GPU 设备详情" size="480px">
      <div v-if="detailDevice">
        <div v-for="row in detailRows" :key="row.label" class="detail-row">
          <span class="detail-label">{{ row.label }}</span>
          <span class="detail-value">{{ row.value }}</span>
        </div>
      </div>
    </el-drawer>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import type { FormInstance, FormRules } from 'element-plus'
import PageState from '@/components/PageState.vue'
import Can from '@/components/Can.vue'
import { gpuApi, clusterApi } from '@/api'
import { useFetch } from '@/utils/useFetch'
import type { GPUDevice, GPUAllocation, GPUVendor, Cluster } from '@/types'

const VENDOR_OPTIONS: { label: string; value: GPUVendor }[] = [
  { label: 'NVIDIA', value: 'nvidia' },
  { label: '燧原 Enflame', value: 'enflame' },
  { label: '摩尔线程', value: 'moore_threads' },
  { label: '国产 X', value: 'domestic_x' },
]

const GPU_STATUS_OPTIONS = [
  { label: '可用', value: 'available' },
  { label: '已分配', value: 'allocated' },
  { label: '维护中', value: 'maintenance' },
  { label: '故障', value: 'fault' },
]

/** skill.md 4.2 容器虚拟化隔离能力 */
const ISOLATION_CAPS = [
  { name: '算力隔离', desc: 'cgroups 容器间计算资源隔离' },
  { name: '显存隔离', desc: 'GPU 显存安全隔离，防止冲突' },
  { name: '显存超发', desc: '显存超额分配，提升利用率' },
  { name: '编解码实例', desc: '视频编解码实例优化处理' },
]

const VENDOR_LABEL: Record<GPUVendor, string> = {
  nvidia: 'NVIDIA',
  enflame: '燧原',
  moore_threads: '摩尔线程',
  domestic_x: '国产X',
}

function vendorLabel(v?: GPUVendor): string {
  return (v && VENDOR_LABEL[v]) ?? v ?? '-'
}
function vendorTagType(v?: GPUVendor) {
  switch (v) {
    case 'nvidia': return 'success'
    case 'enflame': return 'primary'
    case 'moore_threads': return 'warning'
    case 'domestic_x': return 'danger'
    default: return 'info'
  }
}

const STATUS_TYPE: Record<string, string> = {
  available: 'success', active: 'success', completed: 'success', healthy: 'success', success: 'success', running: 'primary',
  allocated: 'warning', pending: 'warning', maintenance: 'warning', paused: 'warning', warning: 'warning',
  fault: 'danger', failed: 'danger', error: 'danger', unhealthy: 'danger', critical: 'danger',
  inactive: 'info', disabled: 'info', idle: 'info', released: 'info',
}
const STATUS_TEXT: Record<string, string> = {
  available: '可用', allocated: '已分配', maintenance: '维护中', fault: '故障', active: '已启用', inactive: '未启用',
  drained: '已排空', running: '运行中', pending: '排队中', completed: '已完成', failed: '失败', error: '失败',
  healthy: '健康', unhealthy: '异常', active_alloc: '活跃',
}
function statusType(s?: string) {
  return (STATUS_TYPE[s ?? ''] ?? 'info') as 'success' | 'warning' | 'danger' | 'info' | 'primary'
}
function statusText(s?: string) {
  return (s && STATUS_TEXT[s]) ?? s ?? '-'
}

// ---------- 筛选 ----------
const keyword = ref('')
const vendorFilter = ref<GPUVendor | ''>('')
const statusFilter = ref<string>('')
const clusterFilter = ref<number | undefined>(undefined)

// ---------- 数据 ----------
const devices = useFetch<GPUDevice[]>(() =>
  gpuApi.devices({
    vendor: vendorFilter.value || undefined,
    status: statusFilter.value || undefined,
    cluster_id: clusterFilter.value,
  }),
)
const allocations = useFetch<GPUAllocation[]>(() => gpuApi.allocations({}))
const clusters = useFetch<Cluster[]>(() => clusterApi.list())

watch([vendorFilter, statusFilter, clusterFilter], () => devices.refetch())

const devicesData = computed(() => devices.data.value ?? [])
const allocationsData = computed(() => allocations.data.value ?? [])
const clustersData = computed(() => clusters.data.value ?? [])

// 节点名 / 型号模糊搜索
const searchedDevices = computed(() => {
  const kw = keyword.value.trim().toLowerCase()
  if (!kw) return devicesData.value
  return devicesData.value.filter(
    (d) => d.node_name.toLowerCase().includes(kw) || (d.model ?? '').toLowerCase().includes(kw),
  )
})

// 分页
const currentPage = ref(1)
const pageSize = 10
const pagedData = computed(() =>
  searchedDevices.value.slice((currentPage.value - 1) * pageSize, currentPage.value * pageSize),
)
watch(searchedDevices, () => (currentPage.value = 1))

// ---------- 统计 ----------
const stats = computed(() => {
  const list = devicesData.value
  return {
    total: list.length,
    available: list.filter((d) => d.status === 'available').length,
    allocated: list.filter((d) => d.status === 'allocated').length,
    maintenance: list.filter((d) => d.status === 'maintenance').length,
    fault: list.filter((d) => d.status === 'fault').length,
  }
})
const vendorDist = computed<Record<string, number>>(() => {
  const dist: Record<string, number> = {}
  for (const d of devicesData.value) {
    if (!d.vendor) continue
    dist[d.vendor] = (dist[d.vendor] ?? 0) + 1
  }
  return dist
})

// 分配粒度分布（1 / 1/2 / 1/4 GPU）
const fracFull = computed(() => allocationsData.value.filter((a) => a.fraction >= 1).length)
const fracHalf = computed(() => allocationsData.value.filter((a) => a.fraction === 0.5).length)
const fracQuarter = computed(() => allocationsData.value.filter((a) => a.fraction === 0.25).length)

/** 设为维护模式 */
async function handleSetMaintenance(row: GPUDevice) {
  try {
    await gpuApi.updateDevice(row.id, { status: 'maintenance' })
    ElMessage.success('已设为维护模式')
    devices.refetch()
  } catch {
    ElMessage.error('操作失败，请稍后重试')
  }
}

// ---------- 表单 ----------
const formRef = ref<FormInstance>()
const dialogVisible = ref(false)
const editingDevice = ref<GPUDevice | null>(null)
const form = reactive({
  node_name: '',
  vendor: 'nvidia' as GPUVendor,
  model: '',
  index: undefined as number | undefined,
  total_memory_gb: undefined as number | undefined,
  allocatable_memory_gb: undefined as number | undefined,
  mig_enabled: false,
  driver_version: '',
  cuda_version: '',
  status: 'available' as GPUDevice['status'],
  cluster_id: undefined as number | undefined,
  details: '',
})
const rules: FormRules = {
  node_name: [{ required: true, message: '请输入节点名', trigger: 'blur' }],
  vendor: [{ required: true, message: '请选择厂商', trigger: 'change' }],
}

function resetForm() {
  Object.assign(form, {
    node_name: '', vendor: 'nvidia', model: '', index: undefined, total_memory_gb: undefined,
    allocatable_memory_gb: undefined, mig_enabled: false, driver_version: '', cuda_version: '',
    status: 'available', cluster_id: undefined, details: '',
  })
}
function openCreate() {
  editingDevice.value = null
  resetForm()
  dialogVisible.value = true
}
function openEdit(row: GPUDevice) {
  editingDevice.value = row
  Object.assign(form, {
    node_name: row.node_name, vendor: row.vendor, model: row.model, index: row.index,
    total_memory_gb: row.total_memory_gb, allocatable_memory_gb: row.allocatable_memory_gb,
    mig_enabled: row.mig_enabled ?? false, driver_version: row.driver_version, cuda_version: row.cuda_version,
    status: row.status ?? 'available', cluster_id: row.cluster_id, details: row.details,
  })
  dialogVisible.value = true
}
async function submitForm() {
  await formRef.value?.validate()
  try {
    if (editingDevice.value) {
      await gpuApi.updateDevice(editingDevice.value.id, { ...form })
      ElMessage.success('GPU 设备更新成功')
    } else {
      await gpuApi.createDevice({ ...form })
      ElMessage.success('GPU 设备创建成功')
    }
    dialogVisible.value = false
    resetForm()
    devices.refetch()
  } catch {
    ElMessage.error('操作失败，请检查必填项后重试')
  }
}
async function handleDelete(id: number) {
  try {
    await gpuApi.deleteDevice(id)
    ElMessage.success('GPU 设备删除成功')
    devices.refetch()
  } catch {
    ElMessage.error('删除失败，请稍后重试')
  }
}

// ---------- 分配 ----------
const allocateVisible = ref(false)
const allocatingDevice = ref<GPUDevice | null>(null)
const allocFormRef = ref<FormInstance>()
const allocForm = reactive({
  fraction: 1 as number,
  memory_gb: undefined as number | undefined,
  job_id: undefined as number | undefined,
  tenant_id: undefined as number | undefined,
  user_id: undefined as number | undefined,
})
function openAllocate(row: GPUDevice) {
  allocatingDevice.value = row
  Object.assign(allocForm, { fraction: 1, memory_gb: undefined, job_id: undefined, tenant_id: undefined, user_id: undefined })
  allocateVisible.value = true
}
async function submitAllocate() {
  if (!allocatingDevice.value) return
  try {
    await gpuApi.allocate({
      device_id: allocatingDevice.value.id,
      fraction: allocForm.fraction,
      memory_gb: allocForm.memory_gb,
      job_id: allocForm.job_id,
      tenant_id: allocForm.tenant_id,
      user_id: allocForm.user_id,
      status: 'active',
    })
    const fracText = allocForm.fraction >= 1 ? '1 GPU' : `${Math.round(1 / allocForm.fraction)} 分之一 GPU`
    ElMessage.success(`已按 ${fracText} 粒度分配`)
    allocateVisible.value = false
    devices.refetch()
    allocations.refetch()
  } catch {
    ElMessage.error('分配失败，请稍后重试')
  }
}

// ---------- 分配记录 drawer ----------
const allocDrawerVisible = ref(false)
const allocDeviceId = ref<number>(0)
const currentAllocations = computed(() =>
  allocationsData.value.filter((a) => a.device_id === allocDeviceId.value),
)
function openAllocations(row: GPUDevice) {
  allocDeviceId.value = row.id
  allocDrawerVisible.value = true
}
async function releaseAllocation(alloc: GPUAllocation) {
  try {
    await gpuApi.release(alloc.id)
    ElMessage.success('GPU 已释放')
    allocations.refetch()
  } catch {
    ElMessage.error('释放失败，请稍后重试')
  }
}

// ---------- 详情 ----------
const detailVisible = ref(false)
const detailDevice = ref<GPUDevice | null>(null)
watch(detailDevice, (v) => { detailVisible.value = !!v })
const detailRows = computed(() => {
  const d = detailDevice.value
  if (!d) return []
  return [
    { label: '节点名', value: d.node_name },
    { label: '厂商', value: vendorLabel(d.vendor) },
    { label: '型号', value: d.model ?? '-' },
    { label: '索引', value: d.index ?? '-' },
    { label: '总显存', value: `${d.total_memory_gb ?? '-'} GB` },
    { label: '已用显存', value: `${d.used_memory_gb ?? '-'} GB` },
    { label: '可分配显存', value: `${d.allocatable_memory_gb ?? '-'} GB` },
    { label: 'MIG', value: d.mig_enabled ? '开启' : '关闭' },
    { label: '驱动版本', value: d.driver_version ?? '-' },
    { label: 'CUDA 版本', value: d.cuda_version ?? '-' },
    { label: '状态', value: statusText(d.status) },
    { label: '利用率', value: `${d.utilization ?? 0}%` },
    { label: '温度', value: `${d.temperature ?? '-'} °C` },
    { label: '功耗', value: `${d.power_draw ?? '-'} W` },
    { label: 'MIG Profiles', value: d.mig_profiles ?? '-' },
    { label: '详情', value: d.details ?? '-' },
  ]
})
</script>

<style scoped>
.toolbar { display: flex; flex-wrap: wrap; gap: 12px; align-items: center; }
.stat-label { font-size: 12.5px; color: var(--mc-text-3); margin-bottom: 6px; }
.stat-value { font-size: 24px; font-weight: 660; color: var(--mc-text-1); }
.stat-unit { font-size: 12px; font-weight: 500; color: var(--mc-text-3); }
.vendor-dist { display: flex; flex-wrap: wrap; gap: 6px; }
.detail-row { display: flex; padding: 8px 0; border-bottom: 1px solid var(--mc-line); }
.detail-label { width: 120px; color: var(--mc-text-3); flex-shrink: 0; }
.detail-value { flex: 1; word-break: break-all; }
.mc-empty-mini { color: var(--mc-text-3); }
.iso-cap { border-left: 3px solid var(--mc-brand, #2f6bff); padding: 8px 12px; border-radius: 8px; background: var(--mc-bg, transparent); }
.iso-cap-name { font-weight: 600; margin-bottom: 4px; }
.iso-cap-desc { font-size: 12px; color: var(--mc-text-3); }
.iso-sub .el-card__header { font-size: 13px; font-weight: 600; }
.mc-mr { margin-right: 6px; }
</style>

// metaclouds-frontend/src/pages/GPUManagement.tsx
﻿import { Can } from '../components/Can';
import React, { memo, useCallback, useMemo, useState } from 'react';
import {
  Card,
  Row,
  Col,
  Statistic,
  Button,
  Space,
  App,
  Modal,
  Form,
  Input,
  Select,
  InputNumber,
  Switch,
  Tag,
  Progress,
  Popconfirm,
  Drawer,
} from 'antd';
import ResponsiveTable from '../components/ResponsiveTable';
import type { ColumnsType } from 'antd/es/table';
import {
  useGetGPUDevicesQuery,
  useCreateGPUDeviceMutation,
  useUpdateGPUDeviceMutation,
  useDeleteGPUDeviceMutation,
  useGetGPUAllocationsQuery,
  useGetClustersQuery,
  useAllocateGPUMutation,
  useReleaseGPUMutation,
} from '../store/api';
import { extractArrayData } from '../utils/api';
import { renderState, EmptyState } from '../components/States';
import StatusCell from '../components/StatusCell';
import type { GPUDevice, GPUVendor, GPUAllocation } from '../types';
import { brand } from '../theme/tokens';

const VENDOR_OPTIONS: { label: string; value: GPUVendor }[] = [
  { label: 'NVIDIA', value: 'nvidia' },
  { label: '燧原 Enflame', value: 'enflame' },
  { label: '摩尔线程', value: 'moore_threads' },
  { label: '国产 X', value: 'domestic_x' },
];

const VENDOR_COLOR: Record<GPUVendor, string> = {
  nvidia: 'green',
  enflame: 'blue',
  moore_threads: 'purple',
  domestic_x: 'orange',
};

const VENDOR_LABEL: Record<GPUVendor, string> = {
  nvidia: 'NVIDIA',
  enflame: '燧原',
  moore_threads: '摩尔线程',
  domestic_x: '国产X',
};

/** 厂商标签：颜色 + 文字，memo 避免重渲染 */
const VendorTag: React.FC<{ vendor: GPUVendor }> = memo(({ vendor }) => (
  <Tag color={VENDOR_COLOR[vendor]}>{VENDOR_LABEL[vendor] ?? vendor}</Tag>
));

/** GPU 设备表单值 */
interface GPUFormValues {
  node_name: string;
  vendor: GPUVendor;
  model?: string;
  index?: number;
  total_memory_gb?: number;
  allocatable_memory_gb?: number;
  mig_enabled?: boolean;
  driver_version?: string;
  cuda_version?: string;
  status?: string;
  cluster_id?: number;
}

const GPUManagement: React.FC = () => {
  const { message } = App.useApp();

  // 筛选状态
  const [vendorFilter, setVendorFilter] = useState<string | undefined>(undefined);
  const [statusFilter, setStatusFilter] = useState<string | undefined>(undefined);
  const [clusterFilter, setClusterFilter] = useState<number | undefined>(undefined);
  const [keyword, setKeyword] = useState<string>('');

  // 详情抽屉
  const [detailDevice, setDetailDevice] = useState<GPUDevice | null>(null);

  // 分配 Modal
  const [allocateVisible, setAllocateVisible] = useState(false);
  const [allocatingDevice, setAllocatingDevice] = useState<GPUDevice | null>(null);
  const [allocateForm] = Form.useForm<{
    fraction: number;
    memory_gb?: number;
    job_id?: number;
    tenant_id?: number;
    user_id?: number;
  }>();

  // 表单
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [editingDevice, setEditingDevice] = useState<GPUDevice | null>(null);
  const [form] = Form.useForm<GPUFormValues>();

  // API
  const { data: devices, isLoading, error, refetch } = useGetGPUDevicesQuery({
    vendor: vendorFilter,
    status: statusFilter,
    cluster_id: clusterFilter,
  });
  const { data: allocations } = useGetGPUAllocationsQuery({});
  const { data: clusters } = useGetClustersQuery(undefined);
  const devicesData = devices ?? [];
  const allocationsData = allocations ?? [];
  const clustersData = extractArrayData(clusters);

  const [createGPUDevice] = useCreateGPUDeviceMutation();
  const [updateGPUDevice] = useUpdateGPUDeviceMutation();
  const [deleteGPUDevice] = useDeleteGPUDeviceMutation();
  const [allocateGPU] = useAllocateGPUMutation();
  const [releaseGPU] = useReleaseGPUMutation();

  // 节点名模糊搜索
  const searchedDevices = useMemo(() => {
    if (!keyword.trim()) return devices ?? [];
    const kw = keyword.trim().toLowerCase();
    return (devices ?? []).filter(
      (d) => d.node_name.toLowerCase().includes(kw) || (d.model ?? '').toLowerCase().includes(kw),
    );
  }, [devices, keyword]);

  // 统计卡片
  const stats = useMemo(() => {
    const total = devicesData.length;
    const allocated = devicesData.filter((d) => d.status === 'allocated').length;
    const available = devicesData.filter((d) => d.status === 'available').length;
    const avgUtil =
      total > 0
        ? Math.round(
            devicesData.reduce((s, d) => s + (d.utilization ?? 0), 0) / total,
          )
        : 0;
    const totalMem = devicesData.reduce((s, d) => s + (d.total_memory_gb ?? 0), 0);
    const usedMem = devicesData.reduce((s, d) => s + (d.used_memory_gb ?? 0), 0);
    // 显存超发：可分配显存 / 总显存 折算超发倍数（>1 表示超发）
    const oversub = devicesData
      .filter((d) => d.total_memory_gb && (d.allocatable_memory_gb ?? 0) > 0)
      .map((d) => (d.allocatable_memory_gb ?? 0) / (d.total_memory_gb ?? 1));
    const avgOversub = oversub.length ? (Math.round((oversub.reduce((a, b) => a + b, 0) / oversub.length) * 100) / 100) : 0;
    // 分配粒度分布：1 / 1/2 / 1/4 / N
    const fracFull = allocationsData.filter((a) => a.fraction >= 1).length;
    const fracHalf = allocationsData.filter((a) => a.fraction === 0.5).length;
    const fracQuarter = allocationsData.filter((a) => a.fraction === 0.25).length;
    return {
      total, allocated, available, avgUtil, totalMem, usedMem,
      avgOversub, fracFull, fracHalf, fracQuarter,
    };
  }, [devicesData, allocationsData]);

  // 打开分配 Modal
  const handleOpenAllocate = useCallback(
    (record: GPUDevice) => {
      setAllocatingDevice(record);
      allocateForm.resetFields();
      allocateForm.setFieldsValue({ fraction: 1 });
      setAllocateVisible(true);
    },
    [allocateForm],
  );

  // 提交分配：1 / 1/2 / 1/4 / N GPU
  const handleSubmitAllocate = useCallback(
    async (values: { fraction: number; memory_gb?: number; job_id?: number; tenant_id?: number; user_id?: number }) => {
      if (!allocatingDevice) return;
      try {
        await allocateGPU({
          device_id: allocatingDevice.id,
          fraction: values.fraction,
          memory_gb: values.memory_gb,
          job_id: values.job_id,
          tenant_id: values.tenant_id,
          user_id: values.user_id,
          status: 'active',
        } as Partial<GPUAllocation>).unwrap();
        message.success(`已按 ${values.fraction >= 1 ? '1 GPU' : `${Math.round(1 / values.fraction)} 分之一 GPU`} 粒度分配`);
        setAllocateVisible(false);
        allocateForm.resetFields();
        refetch();
      } catch {
        message.error('分配失败，请稍后重试');
      }
    },
    [allocatingDevice, allocateGPU, allocateForm, message, refetch],
  );

  // 释放分配
  const handleReleaseAllocation = useCallback(
    async (alloc: GPUAllocation) => {
      try {
        await releaseGPU(alloc.id).unwrap();
        message.success('GPU 已释放');
        refetch();
      } catch {
        message.error('释放失败，请稍后重试');
      }
    },
    [releaseGPU, message, refetch],
  );

  // 打开新建
  const handleOpenCreate = useCallback(() => {
    setEditingDevice(null);
    form.resetFields();
    setIsModalVisible(true);
  }, [form]);

  // 打开编辑
  const handleOpenEdit = useCallback(
    (record: GPUDevice) => {
      setEditingDevice(record);
      form.setFieldsValue({
        node_name: record.node_name,
        vendor: record.vendor,
        model: record.model,
        index: record.index,
        total_memory_gb: record.total_memory_gb,
        allocatable_memory_gb: record.allocatable_memory_gb,
        mig_enabled: record.mig_enabled,
        driver_version: record.driver_version,
        cuda_version: record.cuda_version,
        status: record.status,
        cluster_id: record.cluster_id,
      });
      setIsModalVisible(true);
    },
    [form],
  );

  // 提交表单
  const handleSubmit = useCallback(
    async (values: GPUFormValues) => {
      try {
        if (editingDevice) {
          await updateGPUDevice({ id: editingDevice.id, data: values as Partial<GPUDevice> }).unwrap();
          message.success('GPU 设备更新成功');
        } else {
          await createGPUDevice(values as Partial<GPUDevice>).unwrap();
          message.success('GPU 设备创建成功');
        }
        setIsModalVisible(false);
        form.resetFields();
        refetch();
      } catch {
        message.error('操作失败，请检查必填项后重试');
      }
    },
    [editingDevice, createGPUDevice, updateGPUDevice, form, message, refetch],
  );

  // 删除
  const handleDelete = useCallback(
    async (id: number) => {
      try {
        await deleteGPUDevice(id).unwrap();
        message.success('GPU 设备删除成功');
        refetch();
      } catch {
        message.error('删除失败，请稍后重试');
      }
    },
    [deleteGPUDevice, message, refetch],
  );

  // 设为维护模式
  const handleSetMaintenance = useCallback(
    async (record: GPUDevice) => {
      try {
        await updateGPUDevice({
          id: record.id,
          data: { status: 'maintenance' },
        }).unwrap();
        message.success('已设为维护模式');
        refetch();
      } catch {
        message.error('操作失败，请稍后重试');
      }
    },
    [updateGPUDevice, message, refetch],
  );

  // 设备的分配记录
  const deviceAllocations = useCallback(
    (deviceId: number) => allocationsData.filter((a) => a.device_id === deviceId),
    [allocationsData],
  );

  // 列定义
  const columns = useMemo<ColumnsType<GPUDevice>>(
    () => [
      {
        title: '节点名',
        dataIndex: 'node_name',
        key: 'node_name',
        width: 140,
        render: (v: string, record) => (
          <Button type="link" size="small" style={{ padding: 0 }} onClick={() => setDetailDevice(record)}>
            {v}
          </Button>
        ),
      },
      {
        title: '厂商',
        dataIndex: 'vendor',
        key: 'vendor',
        width: 100,
        render: (v: GPUVendor) => <VendorTag vendor={v} />,
      },
      { title: '型号', dataIndex: 'model', key: 'model', width: 100 },
      {
        title: '索引',
        dataIndex: 'index',
        key: 'index',
        width: 70,
        render: (v: React.ReactNode) => <span className="mc-num">{v}</span>,
      },
      {
        title: '总显存(GB)',
        dataIndex: 'total_memory_gb',
        key: 'total_memory_gb',
        width: 110,
        render: (v: React.ReactNode) => <span className="mc-num">{v}</span>,
      },
      {
        title: '已用显存(GB)',
        dataIndex: 'used_memory_gb',
        key: 'used_memory_gb',
        width: 110,
        render: (v: React.ReactNode) => <span className="mc-num">{v}</span>,
      },
      {
        title: 'MIG',
        dataIndex: 'mig_enabled',
        key: 'mig_enabled',
        width: 70,
        render: (v: boolean) => (v ? <Tag color="blue">开启</Tag> : <Tag>关闭</Tag>),
      },
      { title: '驱动版本', dataIndex: 'driver_version', key: 'driver_version', width: 100 },
      { title: 'CUDA版本', dataIndex: 'cuda_version', key: 'cuda_version', width: 100 },
      {
        title: '状态',
        dataIndex: 'status',
        key: 'status',
        width: 100,
        render: (status: string) => <StatusCell status={status} />,
      },
      {
        title: '利用率',
        dataIndex: 'utilization',
        key: 'utilization',
        width: 130,
        render: (v: number) => <Progress percent={v ?? 0} size="small" />,
      },
      {
        title: '温度(°C)',
        dataIndex: 'temperature',
        key: 'temperature',
        width: 90,
        render: (v: React.ReactNode) => <span className="mc-num">{v}</span>,
      },
      {
        title: '功耗(W)',
        dataIndex: 'power_draw',
        key: 'power_draw',
        width: 90,
        render: (v: React.ReactNode) => <span className="mc-num">{v}</span>,
      },
      {
        title: '操作',
        key: 'action',
        width: 280,
        fixed: 'right',
        render: (_: unknown, record: GPUDevice) => (
          <Space size={4}>
            {record.status === 'available' && (
              <Can perm="gpu:write">
                <Button type="link" size="small" onClick={() => handleOpenAllocate(record)}>
                  分配
                </Button>
              </Can>
            )}
            <Can perm="gpu:write">
              <Button type="link" size="small" onClick={() => handleOpenEdit(record)}>
                编辑
              </Button>
            </Can>
            <Can perm="gpu:write">
              <Button type="link" size="small" onClick={() => handleSetMaintenance(record)}>
                维护
              </Button>
            </Can>
            <Can perm="gpu:write">
              <Popconfirm
                title="删除该 GPU 设备？"
                description="设备记录将被移除，且不可恢复。"
                okText="确认删除"
                cancelText="返回"
                okButtonProps={{ danger: true }}
                onConfirm={() => handleDelete(record.id)}
              >
                <Button type="link" danger size="small">
                  删除
                </Button>
              </Popconfirm>
            </Can>
          </Space>
        ),
      },
    ],
    [handleOpenEdit, handleSetMaintenance, handleDelete, handleOpenAllocate],
  );

  // 展开行：分配记录
  const expandedRowRender = useCallback(
    (record: GPUDevice) => {
      const allocs = deviceAllocations(record.id);
      if (allocs.length === 0) {
        return <div style={{ padding: '8px 16px', color: 'var(--mc-text-3)' }}>暂无分配记录</div>;
      }
      return (
        <div style={{ padding: '8px 16px' }}>
          <ResponsiveTable
            columns={[
              { title: '分配ID', dataIndex: 'id', key: 'id', width: 80 },
              { title: '作业ID', dataIndex: 'job_id', key: 'job_id', width: 90 },
              { title: '租户ID', dataIndex: 'tenant_id', key: 'tenant_id', width: 90 },
              { title: '用户ID', dataIndex: 'user_id', key: 'user_id', width: 90 },
              {
                title: '分配粒度',
                dataIndex: 'fraction',
                key: 'fraction',
                width: 100,
                render: (v: number) => (
                  <Tag color="blue">{v >= 1 ? '1 GPU' : v === 0.5 ? '1/2 GPU' : v === 0.25 ? '1/4 GPU' : `${v} GPU`}</Tag>
                ),
              },
              { title: '显存(GB)', dataIndex: 'memory_gb', key: 'memory_gb', width: 100 },
              {
                title: '状态',
                dataIndex: 'status',
                key: 'status',
                width: 100,
                render: (s: string) => <StatusCell status={s} />,
              },
              { title: '开始时间', dataIndex: 'started_at', key: 'started_at', width: 170 },
              {
                title: '操作',
                key: 'alloc-action',
                width: 90,
                render: (_: unknown, alloc: GPUAllocation) =>
                  alloc.status === 'active' ? (
                    <Can perm="gpu:write">
                      <Popconfirm title="释放该分配？" onConfirm={() => handleReleaseAllocation(alloc)} okText="释放" cancelText="取消">
                        <Button type="link" size="small" danger>释放</Button>
                      </Popconfirm>
                    </Can>
                  ) : (
                    '-'
                  ),
              },
            ]}
            dataSource={allocs}
            rowKey="id"
            pagination={false}
            size="small"
          />
        </div>
      );
    },
    [deviceAllocations, handleReleaseAllocation],
  );

  const state = renderState({
    isLoading,
    error,
    isEmpty: devicesData.length === 0,
    onRetry: refetch,
    skeletonRows: 6,
    skeletonColumns: 10,
    empty: (
      <EmptyState
        title="暂无 GPU 设备"
        description="登记 GPU 设备后，可在此进行细粒度分配、显存管理与状态监控。"
        action={
          <Can perm="gpu:write">
            <Button type="primary" onClick={handleOpenCreate}>
              新增 GPU 设备
            </Button>
          </Can>
        }
      />
    ),
  });

  return (
    <div className="mc-page">
      <a href="#gpu-table" className="mc-skip-link">
        跳转到 GPU 设备列表
      </a>
      <div className="mc-page-head">
        <div className="mc-page-head-main">
          <h1 className="mc-page-title">GPU 细粒度管理</h1>
          <p className="mc-page-desc">
            共 {stats.total} 张 GPU · 已分配 {stats.allocated} · 可用 {stats.available} · 平均利用率 {stats.avgUtil}%
          </p>
        </div>
        <div className="mc-page-head-extra">
          <Can perm="gpu:write">
            <Button type="primary" onClick={handleOpenCreate}>
              新增 GPU 设备
            </Button>
          </Can>
        </div>
      </div>

      {/* 统计卡片 */}
      <Row gutter={[16, 16]} style={{ marginBottom: 16 }}>
        <Col xs={12} sm={12} md={6} lg={6} xl={4}>
          <Card>
            <Statistic title="总 GPU 数" value={stats.total} suffix="张" />
          </Card>
        </Col>
        <Col xs={12} sm={12} md={6} lg={6} xl={4}>
          <Card>
            <Statistic title="已分配" value={stats.allocated} suffix="张" valueStyle={{ color: '#faad14' }} />
          </Card>
        </Col>
        <Col xs={12} sm={12} md={6} lg={6} xl={4}>
          <Card>
            <Statistic title="可用" value={stats.available} suffix="张" valueStyle={{ color: '#52c41a' }} />
          </Card>
        </Col>
        <Col xs={12} sm={12} md={6} lg={6} xl={4}>
          <Card>
            <Statistic title="平均利用率" value={stats.avgUtil} suffix="%" />
          </Card>
        </Col>
        <Col xs={12} sm={12} md={6} lg={6} xl={4}>
          <Card>
            <Statistic title="总显存" value={stats.totalMem} suffix="GB" />
          </Card>
        </Col>
        <Col xs={12} sm={12} md={6} lg={6} xl={4}>
          <Card>
            <Statistic title="已用显存" value={stats.usedMem} suffix="GB" valueStyle={{ color: '#faad14' }} />
          </Card>
        </Col>
        <Col xs={12} sm={12} md={6} lg={6} xl={4}>
          <Card>
            <Statistic title="显存超发比" value={stats.avgOversub} suffix="x" valueStyle={{ color: '#722ed1' }} />
          </Card>
        </Col>
      </Row>

      {/* 容器虚拟化隔离能力 + 隔离引擎 + 分配粒度（skill.md 4.2） */}
      <Card style={{ marginBottom: 16 }} title="容器虚拟化隔离与分配能力">
        <Row gutter={[16, 16]}>
          {[
            { name: '算力隔离', desc: 'cgroups 容器间计算资源隔离' },
            { name: '显存隔离', desc: 'GPU 显存安全隔离，防止冲突' },
            { name: '显存超发', desc: '显存超额分配，提升利用率' },
            { name: '编解码实例', desc: '视频编解码实例优化处理' },
          ].map((c) => (
            <Col xs={12} sm={12} md={6} key={c.name}>
              <div
                style={{
                  borderLeft: `3px solid ${brand[500]}`,
                  padding: '8px 12px',
                  background: 'var(--mc-bg, transparent)',
                  borderRadius: 8,
                }}
              >
                <div style={{ fontWeight: 600, marginBottom: 4 }}>{c.name}</div>
                <div style={{ fontSize: 12, color: 'var(--mc-text-3)' }}>{c.desc}</div>
              </div>
            </Col>
          ))}
          <Col xs={24} sm={12} md={12}>
            <Card size="small" title="隔离引擎">
              <Space wrap>
                <Tag color="blue">用户态虚拟化隔离引擎（轻量高性能）</Tag>
                <Tag color="purple">内核态虚拟化隔离引擎（安全底层隔离）</Tag>
              </Space>
            </Card>
          </Col>
          <Col xs={24} sm={12} md={12}>
            <Card size="small" title="GPU 分配粒度分布">
              <Space wrap>
                <Tag color="green">1 GPU × {stats.fracFull}</Tag>
                <Tag color="blue">1/2 GPU × {stats.fracHalf}</Tag>
                <Tag color="cyan">1/4 GPU × {stats.fracQuarter}</Tag>
                <Tag color="default">N GPU 多卡并行</Tag>
              </Space>
            </Card>
          </Col>
        </Row>
      </Card>

      {/* 筛选器 */}
      <Card style={{ marginBottom: 16 }}>
        <Space wrap>
          <Input.Search
            placeholder="搜索节点名 / 型号"
            allowClear
            style={{ width: 220 }}
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            aria-label="搜索 GPU 节点"
          />
          <Select
            placeholder="厂商筛选"
            allowClear
            style={{ width: 160 }}
            value={vendorFilter}
            onChange={(v) => setVendorFilter(v)}
            options={VENDOR_OPTIONS}
          />
          <Select
            placeholder="状态筛选"
            allowClear
            style={{ width: 140 }}
            value={statusFilter}
            onChange={(v) => setStatusFilter(v)}
            options={[
              { label: '可用', value: 'available' },
              { label: '已分配', value: 'allocated' },
              { label: '维护中', value: 'maintenance' },
              { label: '故障', value: 'fault' },
            ]}
          />
          <Select
            placeholder="集群筛选"
            allowClear
            style={{ width: 180 }}
            value={clusterFilter}
            onChange={(v) => setClusterFilter(v)}
            options={clustersData.map((c: { id: number; name: string }) => ({ label: c.name, value: c.id }))}
          />
        </Space>
      </Card>

      {/* 设备表格 */}
      <Card id="gpu-table">
        {state ?? (
          <ResponsiveTable
            columns={columns}
            dataSource={searchedDevices}
            rowKey="id"
            pagination={{ pageSize: 10, showTotal: (t) => `共 ${t} 条` }}
            scroll={{ x: 1700, y: 520 }}
            expandable={{ expandedRowRender }}
            virtual
          />
        )}
      </Card>

      {/* 新建/编辑 Modal */}
      <Modal
        className="mc-modal-full"
        title={editingDevice ? '编辑 GPU 设备' : '新增 GPU 设备'}
        open={isModalVisible}
        onCancel={() => setIsModalVisible(false)}
        footer={null}
        destroyOnHidden
      >
        <Form form={form} onFinish={handleSubmit} layout="vertical">
          <Row gutter={16}>
            <Col span={12}>
              <Form.Item name="node_name" label="节点名" rules={[{ required: true, message: '请输入节点名' }]}>
                <Input placeholder="例如：gpu-node-01" />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="vendor" label="厂商" rules={[{ required: true, message: '请选择厂商' }]}>
                <Select placeholder="请选择厂商" options={VENDOR_OPTIONS} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="model" label="型号">
                <Input placeholder="例如：A100-80GB" />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="index" label="GPU 索引">
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="total_memory_gb" label="总显存(GB)">
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="allocatable_memory_gb" label="可分配显存(GB)">
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="driver_version" label="驱动版本">
                <Input placeholder="例如：535.129.03" />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="cuda_version" label="CUDA 版本">
                <Input placeholder="例如：12.2" />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="cluster_id" label="所属集群">
                <Select
                  placeholder="请选择集群"
                  allowClear
                  options={clustersData.map((c: { id: number; name: string }) => ({ label: c.name, value: c.id }))}
                />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="status" label="状态">
                <Select
                  placeholder="请选择状态"
                  options={[
                    { label: '可用', value: 'available' },
                    { label: '已分配', value: 'allocated' },
                    { label: '维护中', value: 'maintenance' },
                    { label: '故障', value: 'fault' },
                  ]}
                />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="mig_enabled" label="MIG 开启" valuePropName="checked">
                <Switch />
              </Form.Item>
            </Col>
          </Row>
          <Form.Item style={{ marginBottom: 0 }}>
            <Space>
              <Can perm="gpu:write">
                <Button type="primary" htmlType="submit">
                  {editingDevice ? '保存' : '创建'}
                </Button>
              </Can>
              <Button onClick={() => setIsModalVisible(false)}>取消</Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>

      {/* 详情抽屉 */}
      <Drawer
        title="GPU 设备详情"
        open={detailDevice !== null}
        onClose={() => setDetailDevice(null)}
        width={480}
      >
        {detailDevice && (
          <div>
            <DescriptionsLike label="节点名" value={detailDevice.node_name} />
            <DescriptionsLike label="厂商" value={<VendorTag vendor={detailDevice.vendor} />} />
            <DescriptionsLike label="型号" value={detailDevice.model ?? '-'} />
            <DescriptionsLike label="索引" value={detailDevice.index ?? '-'} />
            <DescriptionsLike label="总显存" value={`${detailDevice.total_memory_gb ?? '-'} GB`} />
            <DescriptionsLike label="已用显存" value={`${detailDevice.used_memory_gb ?? '-'} GB`} />
            <DescriptionsLike label="可分配显存" value={`${detailDevice.allocatable_memory_gb ?? '-'} GB`} />
            <DescriptionsLike label="MIG" value={detailDevice.mig_enabled ? '开启' : '关闭'} />
            <DescriptionsLike label="驱动版本" value={detailDevice.driver_version ?? '-'} />
            <DescriptionsLike label="CUDA 版本" value={detailDevice.cuda_version ?? '-'} />
            <DescriptionsLike label="状态" value={<StatusCell status={detailDevice.status ?? ''} />} />
            <DescriptionsLike label="利用率" value={`${detailDevice.utilization ?? 0}%`} />
            <DescriptionsLike label="温度" value={`${detailDevice.temperature ?? '-'} °C`} />
            <DescriptionsLike label="功耗" value={`${detailDevice.power_draw ?? '-'} W`} />
            <DescriptionsLike label="MIG Profiles" value={detailDevice.mig_profiles ?? '-'} />
            <DescriptionsLike label="详情" value={detailDevice.details ?? '-'} />
          </div>
        )}
      </Drawer>

      {/* GPU 细粒度分配 Modal：1 / 1/2 / 1/4 / N GPU */}
      <Modal
        title={`分配 GPU — ${allocatingDevice?.node_name ?? ''} ${allocatingDevice?.model ?? ''}`}
        open={allocateVisible}
        onCancel={() => setAllocateVisible(false)}
        footer={null}
        destroyOnHidden
      >
        <Form form={allocateForm} onFinish={handleSubmitAllocate} layout="vertical">
          <Form.Item name="fraction" label="GPU 分配粒度" rules={[{ required: true, message: '请选择分配粒度' }]}>
            <Select
              placeholder="请选择分配粒度"
              options={[
                { label: '1 GPU（整卡，计算密集型）', value: 1 },
                { label: '1/2 GPU（中等需求）', value: 0.5 },
                { label: '1/4 GPU（轻量任务）', value: 0.25 },
              ]}
            />
          </Form.Item>
          <Form.Item name="memory_gb" label="分配显存(GB)">
            <InputNumber min={0} style={{ width: '100%' }} placeholder="留空则按粒度自动分配" />
          </Form.Item>
          <Row gutter={16}>
            <Col span={8}>
              <Form.Item name="job_id" label="作业ID">
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="tenant_id" label="租户ID">
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="user_id" label="用户ID">
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
          </Row>
          <Form.Item style={{ marginBottom: 0 }}>
            <Space>
              <Can perm="gpu:write">
                <Button type="primary" htmlType="submit">确认分配</Button>
              </Can>
              <Button onClick={() => setAllocateVisible(false)}>取消</Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

/** 简易描述行（Drawer 内复用） */
const DescriptionsLike: React.FC<{ label: string; value: React.ReactNode }> = ({ label, value }) => (
  <div style={{ display: 'flex', padding: '8px 0', borderBottom: '1px solid var(--mc-border)' }}>
    <span style={{ width: 120, color: 'var(--mc-text-3)', flexShrink: 0 }}>{label}</span>
    <span style={{ flex: 1 }}>{value}</span>
  </div>
);

export default GPUManagement;
