// metaclouds-frontend-vue/src/pages/ResourceManagement.vue
<template>
  <div class="mc-page">
    <div class="mc-page-head">
      <div class="mc-page-head-main">
        <h1 class="mc-page-title">基础资源管理</h1>
        <p class="mc-page-desc">AI 计算资源池 · AI 存储资源 · AI 网络资源 三大基础层总览</p>
      </div>
    </div>

    <!-- GPU 资源概览卡片 -->
    <div class="gpu-overview">
      <el-card shadow="never" v-for="s in vendorStats" :key="s.key">
        <div class="gpu-stat-label">{{ s.label }}</div>
        <div class="gpu-stat-value mc-num">{{ s.value }}<span class="gpu-stat-unit">{{ s.unit }}</span></div>
      </el-card>
    </div>

    <el-card shadow="never" class="mc-mt">
      <!-- 搜索 + 类型筛选工具栏 -->
      <div class="toolbar">
        <el-input
          v-model="keyword"
          placeholder="搜索资源名称 / 型号"
          allow-clear
          class="toolbar-search"
        >
          <template #prefix><el-icon><Search /></el-icon></template>
        </el-input>
        <el-select v-model="typeFilter" placeholder="资源类型" style="width: 160px">
          <el-option label="全部类型" value="" />
          <el-option label="GPU" value="gpu" />
          <el-option label="CPU" value="cpu" />
          <el-option label="内存" value="memory" />
          <el-option label="存储" value="storage" />
          <el-option label="网络" value="network" />
        </el-select>
      </div>

      <PageState
        :loading="loading"
        :error="error"
        :data="resourcesData"
        empty-text="暂无资源，新增节点后将在此分类汇总"
        retry-text="重新加载"
        @retry="refetch"
      >
        <el-table :data="pagedResources" row-key="id" stripe style="width: 100%">
          <el-table-column prop="name" label="名称" min-width="160" show-overflow-tooltip />
          <el-table-column label="类型" width="100">
            <template #default="{ row }">
              <el-tag :type="row.type === 'cpu' ? 'info' : row.type === 'gpu' ? 'primary' : 'success'" size="small">
                {{ typeLabel(row.type) }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column label="状态" width="100">
            <template #default="{ row }">
              <el-tag :type="statusTagType(row.status)" size="small">{{ statusText(row.status) }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column label="总量" width="100" align="right">
            <template #default="{ row }"><span class="mc-num">{{ row.total ?? '-' }}</span></template>
          </el-table-column>
          <el-table-column label="已用" width="100" align="right">
            <template #default="{ row }"><span class="mc-num">{{ row.used ?? '-' }}</span></template>
          </el-table-column>
          <el-table-column label="可用" width="100" align="right">
            <template #default="{ row }"><span class="mc-num">{{ row.available ?? '-' }}</span></template>
          </el-table-column>
          <el-table-column label="利用率" width="160">
            <template #default="{ row }">
              <el-progress :percentage="Math.round(row.utilization ?? 0)" :stroke-width="10" :show-text="true" />
            </template>
          </el-table-column>
          <el-table-column label="厂商" width="110">
            <template #default="{ row }">
              <el-tag v-if="row.vendor" :type="vendorTagType(row.vendor)" size="small">
                {{ vendorLabel(row.vendor) }}
              </el-tag>
              <el-tag v-else size="small">通用</el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="gpu_model" label="型号" width="130">
            <template #default="{ row }">{{ row.gpu_model || '-' }}</template>
          </el-table-column>
          <el-table-column label="操作" width="100" fixed="right">
            <template #default="{ row }">
              <Can :roles="['admin', 'manager']">
                <el-button link type="primary" size="small" @click="openEdit(row)">编辑</el-button>
              </Can>
            </template>
          </el-table-column>
        </el-table>

        <div class="pager">
          <el-pagination
            v-model:current-page="page"
            :page-size="pageSize"
            :total="filteredResources.length"
            layout="total, prev, pager, next"
          />
        </div>
      </PageState>
    </el-card>

    <!-- 编辑资源 -->
    <el-dialog v-model="editVisible" :title="`编辑资源 - ${editing?.name ?? ''}`" width="560px" destroy-on-close>
      <el-form ref="formRef" :model="form" :rules="rules" label-position="vertical">
        <el-form-item label="名称" prop="name">
          <el-input v-model="form.name" />
        </el-form-item>
        <el-form-item label="状态">
          <el-select v-model="form.status" style="width: 100%">
            <el-option label="可用" value="available" />
            <el-option label="繁忙" value="busy" />
            <el-option label="维护" value="maintenance" />
            <el-option label="故障" value="fault" />
          </el-select>
        </el-form-item>
        <el-form-item label="总量">
          <el-input-number v-model="form.total" :min="0" style="width: 100%" />
        </el-form-item>
        <el-form-item label="已用">
          <el-input-number v-model="form.used" :min="0" style="width: 100%" />
        </el-form-item>
        <el-form-item label="可用">
          <el-input-number v-model="form.available" :min="0" style="width: 100%" />
        </el-form-item>
        <el-form-item label="利用率(%)">
          <el-input-number v-model="form.utilization" :min="0" :max="100" style="width: 100%" />
        </el-form-item>
        <el-form-item label="详情">
          <el-input v-model="form.details" type="textarea" :rows="2" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="editVisible = false">取消</el-button>
        <el-button type="primary" :loading="submitting" @click="handleSave">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { Search } from '@element-plus/icons-vue'
import PageState from '@/components/PageState.vue'
import Can from '@/components/Can.vue'
import { resourceApi } from '@/api'
import { useFetch } from '@/utils/useFetch'
import type { Resource, GPUVendor } from '@/types'

const { data, loading, error, refetch } = useFetch<Resource[]>(() => resourceApi.list())
const resourcesData = computed(() => data.value ?? [])

// ---------- 搜索 / 类型筛选 ----------
const keyword = ref('')
const typeFilter = ref('')
const filteredResources = computed(() => {
  const kw = keyword.value.trim().toLowerCase()
  return resourcesData.value.filter((r) => {
    const matchKw =
      !kw ||
      r.name.toLowerCase().includes(kw) ||
      (r.gpu_model ?? '').toLowerCase().includes(kw)
    const matchType = !typeFilter.value || r.type === typeFilter.value
    return matchKw && matchType
  })
})

// ---------- 分页 ----------
const page = ref(1)
const pageSize = 10
const pagedResources = computed(() =>
  filteredResources.value.slice((page.value - 1) * pageSize, page.value * pageSize),
)

// ---------- GPU 概览 ----------
const VENDOR_LABEL: Record<GPUVendor, string> = {
  nvidia: 'NVIDIA',
  enflame: '燧原',
  moore_threads: '摩尔线程',
  domestic_x: '国产 X',
}
const vendorStats = computed(() => {
  const gpuList = resourcesData.value.filter((r) => r.type === 'gpu')
  const byVendor = (v: GPUVendor) => gpuList.filter((r) => r.vendor === v).length
  const cpuCores = resourcesData.value
    .filter((r) => r.type === 'cpu')
    .reduce((s, r) => s + (Number(r.total) || 0), 0)
  return [
    { key: 'nvidia', label: 'NVIDIA', value: byVendor('nvidia'), unit: '台' },
    { key: 'enflame', label: '燧原 Enflame', value: byVendor('enflame'), unit: '台' },
    { key: 'moore_threads', label: '摩尔线程', value: byVendor('moore_threads'), unit: '台' },
    { key: 'domestic_x', label: '国产 X', value: byVendor('domestic_x'), unit: '台' },
    { key: 'cpu', label: 'CPU 资源', value: cpuCores, unit: '核' },
  ]
})

// ---------- 编辑 ----------
const editVisible = ref(false)
const editing = ref<Resource | null>(null)
const submitting = ref(false)
const formRef = ref<FormInstance>()

const form = reactive({
  name: '',
  status: 'available',
  total: 0,
  used: 0,
  available: 0,
  utilization: 0,
  details: '',
})
const rules: FormRules = {
  name: [{ required: true, message: '请输入资源名称', trigger: 'blur' }],
}

function openEdit(row: Resource) {
  editing.value = row
  Object.assign(form, {
    name: row.name,
    status: row.status,
    total: row.total ?? 0,
    used: row.used ?? 0,
    available: row.available ?? 0,
    utilization: Math.round(row.utilization ?? 0),
    details: row.details ?? '',
  })
  editVisible.value = true
}

async function handleSave() {
  if (!formRef.value || !editing.value) return
  try {
    await formRef.value.validate()
  } catch {
    return
  }
  submitting.value = true
  try {
    await resourceApi.update(editing.value.id, { ...form })
    ElMessage.success('资源更新成功')
    editVisible.value = false
    refetch()
  } catch {
    ElMessage.error('资源更新失败，请稍后重试')
  } finally {
    submitting.value = false
  }
}

// ---------- 展示辅助 ----------
function typeLabel(t: string) {
  return { gpu: 'GPU', cpu: 'CPU', memory: '内存', storage: '存储', network: '网络' }[t] ?? t
}
function vendorLabel(v: GPUVendor) {
  return VENDOR_LABEL[v] ?? v
}
function vendorTagType(v: GPUVendor): 'success' | 'primary' | 'warning' | 'danger' {
  const map: Record<GPUVendor, 'success' | 'primary' | 'warning' | 'danger'> = { nvidia: 'success', enflame: 'primary', moore_threads: 'warning', domestic_x: 'danger' }
  return map[v] ?? 'primary'
}
function statusText(status?: string) {
  const map: Record<string, string> = {
    available: '可用',
    busy: '繁忙',
    maintenance: '维护',
    fault: '故障',
    active: '活跃',
    inactive: '非活跃',
    running: '运行中',
  }
  return map[status ?? ''] ?? status ?? '-'
}
function statusTagType(status?: string): 'success' | 'warning' | 'danger' | 'info' | 'primary' {
  if (status === 'available' || status === 'active' || status === 'running') return 'success'
  if (status === 'maintenance') return 'warning'
  if (status === 'fault' || status === 'failed' || status === 'error') return 'danger'
  if (status === 'busy') return 'primary'
  return 'info'
}
</script>

<style scoped>
.gpu-overview {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: var(--mc-gap);
}
.gpu-stat-label { font-size: 13px; color: var(--mc-text-3); margin-bottom: 6px; }
.gpu-stat-value { font-size: 28px; font-weight: 680; color: var(--mc-text-1); }
.gpu-stat-unit { font-size: 14px; font-weight: 400; color: var(--mc-text-3); margin-left: 4px; }

.toolbar { display: flex; gap: 12px; margin-bottom: 16px; flex-wrap: wrap; }
.toolbar-search { flex: 1; min-width: 240px; max-width: 380px; }
.pager { display: flex; justify-content: flex-end; margin-top: 16px; }
</style>

// metaclouds-frontend/src/pages/ResourceManagement.tsx
import React, { useMemo, useState } from 'react';
import { Card, Progress, Tag, Select, Space, Input, Row, Col, Statistic, Tabs, Typography } from 'antd';
import ResponsiveTable from '../components/ResponsiveTable';
import type { ColumnsType } from 'antd/es/table';
import { useGetResourcesQuery } from '../store/api';
import { extractArrayData } from '../utils/api';
import { renderState, EmptyState } from '../components/States';
import StatusCell from '../components/StatusCell';
import type { Resource, GPUVendor } from '../types';
import { brand } from '../theme/tokens';

const { Text } = Typography;

const VENDOR_OPTIONS: { label: string; value: GPUVendor }[] = [
  { label: 'NVIDIA', value: 'nvidia' },
  { label: '燧原', value: 'enflame' },
  { label: '摩尔线程', value: 'moore_threads' },
  { label: '国产 X', value: 'domestic_x' },
];

const VENDOR_COLOR: Record<GPUVendor, string> = {
  nvidia: 'green',
  enflame: 'blue',
  moore_threads: 'purple',
  domestic_x: 'orange',
};

const VENDOR_LABEL: Record<GPUVendor, string> = {
  nvidia: 'NVIDIA',
  enflame: '燧原',
  moore_threads: '摩尔线程',
  domestic_x: '国产X',
};

/** skill.md 4.1 — AI存储资源五类 */
const STORAGE_CAPABILITIES = [
  { key: 'capacity', name: '海量存储', desc: '大容量数据存储，用于存储大规模数据集' },
  { key: 'parallel', name: '并行文件存储', desc: 'Lustre/BeeGFS 并行文件系统，支持高并发数据访问' },
  { key: 'dense', name: '高密度存储', desc: '高密度存储方案，提高存储密度与性价比' },
  { key: 'allflash', name: '全闪存存储', desc: '全闪存高性能存储，低延迟、高吞吐' },
  { key: 'object', name: '对象存储', desc: '分布式对象存储，存放非结构化数据与模型文件' },
];

/** skill.md 4.1 — AI网络资源五类 */
const NETWORK_CAPABILITIES = [
  { key: 'roce', name: 'RoCE网络', desc: '基于以太网的 RDMA，高速节点间通信' },
  { key: 'ib', name: 'IB网络', desc: 'InfiniBand 高速网络，低延迟高带宽' },
  { key: 'lb', name: '负载均衡', desc: '网络流量负载均衡，优化流量分布' },
  { key: 'mgmt', name: '管理网', desc: '集群管理网络，承载节点间管理通信' },
  { key: 'storage_net', name: '存储网', desc: '存储专用网络，服务存储系统间通信' },
];

/** 能力卡：科技蓝渐变标题条 */
const CapabilityCard: React.FC<{ name: string; desc: string }> = ({ name, desc }) => (
  <Card size="small" style={{ height: '100%' }}>
    <div
      style={{
        display: 'inline-block',
        padding: '2px 10px',
        borderRadius: 999,
        background: brand.grad,
        color: '#fff',
        fontSize: 12,
        marginBottom: 8,
      }}
    >
      {name}
    </div>
    <Text type="secondary" style={{ fontSize: 12 }}>{desc}</Text>
  </Card>
);

const ResourceManagement: React.FC = () => {
  const [activeTab, setActiveTab] = useState<string>('compute');
  const [vendorFilter, setVendorFilter] = useState<string | undefined>(undefined);
  const [keyword, setKeyword] = useState<string>('');

  const { data: resources, isLoading, error, refetch } = useGetResourcesQuery(undefined);
  const resourcesData = extractArrayData<Resource>(resources);

  // 名称模糊搜索
  const searchedData = useMemo(() => {
    if (!keyword.trim()) return resourcesData;
    const kw = keyword.trim().toLowerCase();
    return resourcesData.filter(
      (r) => r.name.toLowerCase().includes(kw) || (r.gpu_model ?? '').toLowerCase().includes(kw),
    );
  }, [resourcesData, keyword]);

  // 计算资源（gpu / cpu）
  const computeData = useMemo(() => {
    const list = searchedData.filter((r) => r.type === 'gpu' || r.type === 'cpu');
    if (!vendorFilter) return list;
    return list.filter((r) => r.vendor === vendorFilter);
  }, [searchedData, vendorFilter]);

  // 存储 / 网络资源
  const storageData = useMemo(() => searchedData.filter((r) => r.type === 'storage' || r.type === 'memory'), [searchedData]);
  const networkData = useMemo(() => searchedData.filter((r) => r.type === 'network'), [searchedData]);

  // 计算资源分厂商统计
  const vendorStats = useMemo(() => {
    const gpuList = resourcesData.filter((r) => r.type === 'gpu');
    const byVendor = (v: GPUVendor) => gpuList.filter((r) => r.vendor === v).length;
    const cpuCount = resourcesData.filter((r) => r.type === 'cpu').reduce((s, r) => s + (r.total ?? 0), 0);
    return {
      nvidia: byVendor('nvidia'),
      enflame: byVendor('enflame'),
      moore_threads: byVendor('moore_threads'),
      domestic_x: byVendor('domestic_x'),
      cpu: cpuCount,
    };
  }, [resourcesData]);

  // 列配置：计算资源
  const computeColumns = useMemo<ColumnsType<Resource>>(() => [
    { title: 'ID', dataIndex: 'id', key: 'id', width: 80, render: (v: React.ReactNode) => <span className="mc-mono">{v}</span> },
    { title: '名称', dataIndex: 'name', key: 'name' },
    { title: '类型', dataIndex: 'type', key: 'type', render: (type: string) => <Tag color={type === 'cpu' ? 'geekblue' : 'blue'}>{type === 'cpu' ? 'CPU' : 'GPU'}</Tag> },
    {
      title: '厂商',
      dataIndex: 'vendor',
      key: 'vendor',
      width: 100,
      render: (v?: GPUVendor) => (v ? <Tag color={VENDOR_COLOR[v]}>{VENDOR_LABEL[v]}</Tag> : <Tag>通用</Tag>),
    },
    { title: 'GPU型号', dataIndex: 'gpu_model', key: 'gpu_model', width: 120, render: (v: React.ReactNode) => v ?? '-' },
    {
      title: '显存总量(MB)',
      dataIndex: 'vram_total_mb',
      key: 'vram_total_mb',
      width: 120,
      render: (v: React.ReactNode) => <span className="mc-num">{v ?? '-'}</span>,
    },
    {
      title: '显存已用(MB)',
      dataIndex: 'vram_used_mb',
      key: 'vram_used_mb',
      width: 120,
      render: (v: React.ReactNode) => <span className="mc-num">{v ?? '-'}</span>,
    },
    {
      title: '显存超发比率',
      dataIndex: 'vram_oversubscription_ratio',
      key: 'vram_oversubscription_ratio',
      width: 110,
      render: (v: number) => (v != null ? <Tag color="purple">{v}x</Tag> : '-'),
    },
    {
      title: 'MIG',
      dataIndex: 'mig_enabled',
      key: 'mig_enabled',
      width: 80,
      render: (v: boolean) => (v ? <Tag color="blue">开启</Tag> : <Tag>关闭</Tag>),
    },
    { title: '状态', dataIndex: 'status', key: 'status', width: 100, render: (status: string) => <StatusCell status={status} /> },
    { title: '总量', dataIndex: 'total', key: 'total', width: 90, render: (v: React.ReactNode) => <span className="mc-num">{v ?? '-'}</span> },
    { title: '已用', dataIndex: 'used', key: 'used', width: 90, render: (v: React.ReactNode) => <span className="mc-num">{v ?? '-'}</span> },
    { title: '可用', dataIndex: 'available', key: 'available', width: 90, render: (v: React.ReactNode) => <span className="mc-num">{v ?? '-'}</span> },
    {
      title: '利用率',
      dataIndex: 'utilization',
      key: 'utilization',
      width: 140,
      render: (util: number) => <Progress percent={util ?? 0} size="small" />,
    },
  ], []);

  // 通用资源列（存储 / 网络）
  const genericColumns = useMemo<ColumnsType<Resource>>(() => [
    { title: 'ID', dataIndex: 'id', key: 'id', width: 80, render: (v: React.ReactNode) => <span className="mc-mono">{v}</span> },
    { title: '名称', dataIndex: 'name', key: 'name' },
    { title: '类型', dataIndex: 'type', key: 'type', width: 110, render: (type: string) => <Tag color="cyan">{type}</Tag> },
    { title: '状态', dataIndex: 'status', key: 'status', width: 100, render: (status: string) => <StatusCell status={status} /> },
    { title: '总量', dataIndex: 'total', key: 'total', width: 100, render: (v: React.ReactNode) => <span className="mc-num">{v ?? '-'}</span> },
    { title: '已用', dataIndex: 'used', key: 'used', width: 100, render: (v: React.ReactNode) => <span className="mc-num">{v ?? '-'}</span> },
    { title: '可用', dataIndex: 'available', key: 'available', width: 100, render: (v: React.ReactNode) => <span className="mc-num">{v ?? '-'}</span> },
    {
      title: '利用率',
      dataIndex: 'utilization',
      key: 'utilization',
      width: 140,
      render: (util: number) => <Progress percent={util ?? 0} size="small" />,
    },
    { title: '详情', dataIndex: 'details', key: 'details', render: (v: React.ReactNode) => v ?? '-' },
  ], []);

  const state = renderState({
    isLoading,
    error,
    isEmpty: resourcesData.length === 0,
    onRetry: refetch,
    skeletonRows: 6,
    skeletonColumns: 8,
    empty: (
      <EmptyState title="暂无资源" description="还没有登记任何算力 / 存储 / 网络资源，新增节点后将在此分类汇总。" />
    ),
  });

  const renderTable = (data: Resource[], columns: ColumnsType<Resource>, emptyText: string) => {
    if (state) return state;
    if (data.length === 0) {
      return <EmptyState title={emptyText} description="当前分类下暂无登记资源。" />;
    }
    return (
      <ResponsiveTable
        columns={columns}
        dataSource={data}
        rowKey="id"
        pagination={{ pageSize: 10, showTotal: (t) => `共 ${t} 条` }}
        scroll={{ x: 1500, y: 480 }}
        virtual
      />
    );
  };

  return (
    <div className="mc-page">
      <div className="mc-page-head">
        <div className="mc-page-head-main">
          <h1 className="mc-page-title">基础资源管理</h1>
          <p className="mc-page-desc">AI 计算资源池 · AI 存储资源 · AI 网络资源 三大基础层总览</p>
        </div>
      </div>

      <Card style={{ marginBottom: 16 }}>
        <Space wrap>
          <Input.Search
            placeholder="搜索资源名称 / GPU 型号"
            allowClear
            style={{ width: 260 }}
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            aria-label="搜索资源"
          />
          {activeTab === 'compute' && (
            <Select
              placeholder="厂商筛选"
              allowClear
              style={{ width: 180 }}
              value={vendorFilter}
              onChange={(v) => setVendorFilter(v)}
              options={VENDOR_OPTIONS}
            />
          )}
        </Space>
      </Card>

      <Tabs
        activeKey={activeTab}
        onChange={setActiveTab}
        items={[
          {
            key: 'compute',
            label: 'AI 计算资源池',
            children: (
              <div>
                {/* 多厂商 GPU + CPU 统计卡 */}
                <Row gutter={[16, 16]} style={{ marginBottom: 16 }}>
                  <Col xs={12} sm={8} md={5} lg={4}>
                    <Card><Statistic title="NVIDIA" value={vendorStats.nvidia} suffix="台" /></Card>
                  </Col>
                  <Col xs={12} sm={8} md={5} lg={4}>
                    <Card><Statistic title="燧原 Enflame" value={vendorStats.enflame} suffix="台" /></Card>
                  </Col>
                  <Col xs={12} sm={8} md={5} lg={4}>
                    <Card><Statistic title="摩尔线程" value={vendorStats.moore_threads} suffix="台" /></Card>
                  </Col>
                  <Col xs={12} sm={8} md={5} lg={4}>
                    <Card><Statistic title="国产 X" value={vendorStats.domestic_x} suffix="台" /></Card>
                  </Col>
                  <Col xs={12} sm={8} md={5} lg={4}>
                    <Card><Statistic title="CPU 资源" value={vendorStats.cpu} suffix="核" /></Card>
                  </Col>
                </Row>
                <Card>
                  {renderTable(computeData, computeColumns, '暂无计算资源')}
                </Card>
              </div>
            ),
          },
          {
            key: 'storage',
            label: 'AI 存储资源',
            children: (
              <div>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 16, marginBottom: 16 }}>
                  {STORAGE_CAPABILITIES.map((c) => (
                    <div key={c.key} style={{ flex: '1 1 200px', minWidth: 200 }}>
                      <CapabilityCard name={c.name} desc={c.desc} />
                    </div>
                  ))}
                </div>
                <Card>
                  {renderTable(storageData, genericColumns, '暂无存储资源')}
                </Card>
              </div>
            ),
          },
          {
            key: 'network',
            label: 'AI 网络资源',
            children: (
              <div>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 16, marginBottom: 16 }}>
                  {NETWORK_CAPABILITIES.map((c) => (
                    <div key={c.key} style={{ flex: '1 1 200px', minWidth: 200 }}>
                      <CapabilityCard name={c.name} desc={c.desc} />
                    </div>
                  ))}
                </div>
                <Card>
                  {renderTable(networkData, genericColumns, '暂无网络资源')}
                </Card>
              </div>
            ),
          },
        ]}
      />
    </div>
  );
};

export default ResourceManagement;
