// metaclouds-frontend/src/pages/AccelerationSuiteManagement.tsx
import { Can } from '../components/Can';
import React, { useCallback, useMemo, useState } from 'react';
import { Card, Statistic, Drawer, Descriptions, Tag, Switch, App, Button, Space, Modal, Form, Input, Select, Row, Col } from 'antd';
import ResponsiveTable from '../components/ResponsiveTable';
import type { ColumnsType } from 'antd/es/table';
import { useNavigate } from 'react-router-dom';
import { useGetAccelerationSuitesQuery, useUpdateAccelerationSuiteMutation } from '../store/api';
import { extractArrayData } from '../utils/api';
import { renderState, EmptyState } from '../components/States';
import StatusCell from '../components/StatusCell';
import type { AccelerationSuite, GPUVendor } from '../types';

const CATEGORY_OPTIONS = [
  { label: '数据加速', value: 'fluid_cache' },
  { label: '分布式训练', value: 'distributed_training' },
  { label: '推理加速', value: 'inference' },
  { label: '通信优化', value: 'communication' },
];

const VENDOR_OPTIONS: { label: string; value: GPUVendor }[] = [
  { label: 'NVIDIA', value: 'nvidia' },
  { label: '燧原', value: 'enflame' },
  { label: '摩尔线程', value: 'moore_threads' },
  { label: '国产 X', value: 'domestic_x' },
];

/** config_json 中常见键 → 友好中文名（skill.md 4.4 细分能力） */
const CONFIG_LABELS: Record<string, string> = {
  runtime: '运行时',
  cache_capacity_gb: '缓存容量(GB)',
  replicas: '副本数',
  medium_type: '缓存介质',
  prefetch_enabled: '数据预取',
  prefetch_policy: '预取策略',
  compression_enabled: '数据压缩',
  metadata_acceleration_enabled: '元数据加速',
  cache_hit_rate: '缓存命中率',
  parallel_strategy: '并行策略',
  world_size: '世界大小',
  tensor_parallel_size: '张量并行度',
  pipeline_stages: '流水线段数',
  deepspeed_enabled: 'DeepSpeed',
  megatron_enabled: 'Megatron-LM',
  communication_backend: '通信后端',
  nccl_config: 'NCCL 配置',
  gradient_compression: '梯度通信压缩',
  backend: '推理后端引擎',
  precision: '计算精度',
  quantization_enabled: '模型量化',
  batch_size: '批大小',
  dynamic_batching: '动态批处理',
  max_batch_size: '最大批大小',
  max_latency_ms: '最大时延(ms)',
  operator_fusion: '算子融合',
};

/** 加速套件表单值 */
interface SuiteFormValues {
  config_json?: string;
  category?: 'fluid_cache' | 'distributed_training' | 'inference' | 'communication';
  vendor?: GPUVendor;
}

/** 安全解析 config_json */
const parseConfig = (raw?: string): Record<string, unknown> => {
  if (!raw) return {};
  try {
    const v = JSON.parse(raw);
    return v && typeof v === 'object' ? (v as Record<string, unknown>) : {};
  } catch {
    return {};
  }
};

const AccelerationSuiteManagement: React.FC = () => {
  const { message } = App.useApp();
  const navigate = useNavigate();
  const { data: suites, isLoading, error, refetch } = useGetAccelerationSuitesQuery(undefined);
  const suitesData = useMemo(() => extractArrayData<AccelerationSuite>(suites), [suites]);
  const [updateSuite] = useUpdateAccelerationSuiteMutation();

  const [editModalVisible, setEditModalVisible] = useState(false);
  const [editingSuite, setEditingSuite] = useState<AccelerationSuite | null>(null);
  const [form] = Form.useForm<SuiteFormValues>();

  // 分类筛选
  const [categoryFilter, setCategoryFilter] = useState<string>('all');

  // 详情 Drawer
  const [detailVisible, setDetailVisible] = useState(false);
  const [detailSuite, setDetailSuite] = useState<AccelerationSuite | null>(null);

  const handleToggle = useCallback(
    async (id: number, enabled: boolean) => {
      try {
        await updateSuite({ id, enabled }).unwrap();
        message.success(`加速套件${enabled ? '启用' : '禁用'}成功`);
        refetch();
      } catch {
        message.error('操作失败，请稍后重试');
      }
    },
    [updateSuite, message, refetch],
  );

  const handleOpenEdit = useCallback(
    (record: AccelerationSuite) => {
      setEditingSuite(record);
      form.setFieldsValue({
        config_json: record.config_json,
        category: record.category,
        vendor: record.vendor,
      });
      setEditModalVisible(true);
    },
    [form],
  );

  const handleOpenDetail = useCallback((record: AccelerationSuite) => {
    setDetailSuite(record);
    setDetailVisible(true);
  }, []);

  const handleSaveEdit = useCallback(
    async (values: SuiteFormValues) => {
      if (!editingSuite) return;
      try {
        await updateSuite({ id: editingSuite.id, ...values }).unwrap();
        message.success('加速套件更新成功');
        setEditModalVisible(false);
        form.resetFields();
        refetch();
      } catch {
        message.error('更新失败，请稍后重试');
      }
    },
    [editingSuite, updateSuite, form, message, refetch],
  );

  // 分类统计
  const categoryStats = useMemo(() => {
    const stats: Record<string, { total: number; enabled: number }> = {};
    suitesData.forEach((s) => {
      const key = s.category ?? 'other';
      if (!stats[key]) stats[key] = { total: 0, enabled: 0 };
      stats[key].total += 1;
      if (s.enabled) stats[key].enabled += 1;
    });
    return stats;
  }, [suitesData]);

  const filteredSuites = useMemo(
    () => (categoryFilter === 'all' ? suitesData : suitesData.filter((s) => s.category === categoryFilter)),
    [suitesData, categoryFilter],
  );

  const columns: ColumnsType<AccelerationSuite> = useMemo(
    () => [
      { title: 'ID', dataIndex: 'id', key: 'id', width: 70, render: (v: React.ReactNode) => <span className="mc-mono">{v}</span> },
      { title: '名称', dataIndex: 'name', key: 'name' },
      { title: '类型', dataIndex: 'type', key: 'type', width: 90, render: (type: string) => <Tag>{type}</Tag> },
      {
        title: '类别',
        dataIndex: 'category',
        key: 'category',
        width: 110,
        render: (v: string) => {
          const opt = CATEGORY_OPTIONS.find((o) => o.value === v);
          return opt ? <Tag color="blue">{opt.label}</Tag> : '-';
        },
      },
      {
        title: '厂商',
        dataIndex: 'vendor',
        key: 'vendor',
        width: 90,
        render: (v: GPUVendor) => (v ? <Tag color="green">{v}</Tag> : '-'),
      },
      { title: '版本', dataIndex: 'version', key: 'version', width: 90 },
      { title: '状态', dataIndex: 'status', key: 'status', width: 90, render: (status: string) => <StatusCell status={status} /> },
      {
        title: '启用',
        key: 'enabled',
        width: 80,
        render: (_: unknown, record: AccelerationSuite) => (
          <Can perm="acceleration:write">
            <Switch checked={record.enabled} onChange={(checked) => handleToggle(record.id, checked)} />
          </Can>
        ),
      },
      {
        title: '操作',
        key: 'action',
        width: 140,
        render: (_: unknown, record: AccelerationSuite) => (
          <Space size={0}>
            <Button type="link" size="small" onClick={() => handleOpenDetail(record)}>
              详情
            </Button>
            <Can perm="acceleration:write">
              <Button type="link" size="small" onClick={() => handleOpenEdit(record)}>
                编辑
              </Button>
            </Can>
          </Space>
        ),
      },
    ],
    [handleToggle, handleOpenEdit, handleOpenDetail],
  );

  const state = renderState({
    isLoading,
    error,
    isEmpty: filteredSuites.length === 0,
    onRetry: refetch,
    skeletonRows: 5,
    skeletonColumns: 7,
    empty: (
      <EmptyState
        title="暂无加速套件"
        description={categoryFilter === 'all' ? '还没有登记任何加速套件。' : '该分类下暂无加速套件。'}
      />
    ),
  });

  const detailConfig = detailSuite ? parseConfig(detailSuite.config_json) : {};
  const detailEntries = Object.entries(detailConfig);

  return (
    <div className="mc-page">
      <div className="mc-page-head">
        <div className="mc-page-head-main">
          <h1 className="mc-page-title">加速套件管理</h1>
          <p className="mc-page-desc">
            共 {suitesData.length} 个加速套件 · 数据加速 / 分布式训练 / 推理加速 / 通信优化
          </p>
        </div>
        <div className="mc-page-head-extra">
          <Button onClick={() => navigate('/datasets')}>数据集与缓存</Button>
        </div>
      </div>

      {/* 分类汇总卡片 */}
      <Row gutter={[16, 16]} style={{ marginBottom: 16 }}>
        {[
          { key: 'fluid_cache', label: '数据加速', hint: 'Fluid 缓存 / 预取 / 压缩' },
          { key: 'distributed_training', label: '分布式训练', hint: 'NCCL / DeepSpeed / 并行' },
          { key: 'inference', label: '推理加速', hint: 'TensorRT / 量化 / 批处理' },
          { key: 'communication', label: '通信优化', hint: '梯度通信 / 通信策略' },
        ].map((c) => (
          <Col xs={12} sm={12} md={6} key={c.key}>
            <Card
              size="small"
              onClick={() => setCategoryFilter(categoryFilter === c.key ? 'all' : c.key)}
              style={{ cursor: 'pointer', borderColor: categoryFilter === c.key ? '#1677ff' : undefined }}
            >
              <Statistic
                title={c.label}
                value={categoryStats[c.key]?.total ?? 0}
                suffix={
                  <span style={{ fontSize: 12, color: 'var(--mc-text-3)' }}>
                    启用 {categoryStats[c.key]?.enabled ?? 0}
                  </span>
                }
              />
              <div style={{ fontSize: 12, color: 'var(--mc-text-3)', marginTop: 4 }}>{c.hint}</div>
            </Card>
          </Col>
        ))}
      </Row>

      <Card>
        {state ?? (
          <ResponsiveTable
            columns={columns}
            dataSource={filteredSuites}
            rowKey="id"
            pagination={{ pageSize: 10, showTotal: (t) => `共 ${t} 条` }}
            scroll={{ x: 1080 }}
          />
        )}
      </Card>

      {/* 编辑 Modal */}
      <Modal
        title={`编辑加速套件 - ${editingSuite?.name ?? ''}`}
        open={editModalVisible}
        onCancel={() => setEditModalVisible(false)}
        footer={null}
        destroyOnHidden
        width={600}
      >
        <Form form={form} onFinish={handleSaveEdit} layout="vertical">
          <Row gutter={16}>
            <Col span={12}>
              <Form.Item name="category" label="类别">
                <Select placeholder="请选择类别" allowClear options={CATEGORY_OPTIONS} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="vendor" label="厂商">
                <Select placeholder="请选择厂商" allowClear options={VENDOR_OPTIONS} />
              </Form.Item>
            </Col>
            <Col span={24}>
              <Form.Item name="config_json" label="Config JSON">
                <Input.TextArea rows={6} placeholder='例如：{"runtime":"alluxio","cache_capacity_gb":100}' />
              </Form.Item>
            </Col>
          </Row>
          <Form.Item style={{ marginBottom: 0 }}>
            <Space>
              <Can perm="acceleration:write">
                <Button type="primary" htmlType="submit">保存</Button>
              </Can>
              <Button onClick={() => setEditModalVisible(false)}>取消</Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>

      {/* 详情 Drawer：解析 config_json 展示细分能力 */}
      <Drawer
        title={`加速套件详情 - ${detailSuite?.name ?? ''}`}
        open={detailVisible}
        onClose={() => setDetailVisible(false)}
        width={560}
      >
        {detailSuite && (
          <Descriptions column={1} bordered size="small">
            <Descriptions.Item label="名称">{detailSuite.name}</Descriptions.Item>
            <Descriptions.Item label="类型">{detailSuite.type}</Descriptions.Item>
            <Descriptions.Item label="类别">
              {CATEGORY_OPTIONS.find((o) => o.value === detailSuite.category)?.label ?? detailSuite.category ?? '-'}
            </Descriptions.Item>
            <Descriptions.Item label="厂商">{detailSuite.vendor ?? '-'}</Descriptions.Item>
            <Descriptions.Item label="版本">{detailSuite.version ?? '-'}</Descriptions.Item>
            <Descriptions.Item label="状态">
              <StatusCell status={detailSuite.status ?? ''} />
            </Descriptions.Item>
            <Descriptions.Item label="描述">{detailSuite.description ?? '-'}</Descriptions.Item>
          </Descriptions>
        )}

        <Card size="small" title="细分能力配置" style={{ marginTop: 16 }}>
          {detailEntries.length > 0 ? (
            <Descriptions column={1} size="small">
              {detailEntries.map(([k, v]) => (
                <Descriptions.Item key={k} label={CONFIG_LABELS[k] ?? k}>
                  {typeof v === 'boolean' ? (v ? <Tag color="green">开</Tag> : <Tag>关</Tag>) : String(v)}
                </Descriptions.Item>
              ))}
            </Descriptions>
          ) : (
            <EmptyState title="未配置细分能力" description="该套件尚未填写 config_json 能力参数。" />
          )}
        </Card>
      </Drawer>
    </div>
  );
};

export default AccelerationSuiteManagement;

// metaclouds-frontend-vue/src/pages/AccelerationSuiteManagement.vue
<template>
  <div class="mc-page">
    <div class="mc-page-head">
      <div class="mc-page-head-main">
        <h1 class="mc-page-title">加速套件管理</h1>
        <p class="mc-page-desc">共 {{ suites.length }} 个加速套件 · 数据加速 / 分布式训练 / 推理加速 / 通信优化</p>
      </div>
    </div>

    <!-- 分类汇总卡片（点击切换分类筛选） -->
    <el-row :gutter="16" class="stat-row">
      <el-col
        v-for="c in categoryCards"
        :key="c.key"
        :xs="12"
        :sm="12"
        :md="6"
      >
        <el-card
          shadow="hover"
          :class="['stat-card', { 'is-active': categoryFilter === c.key }]"
          @click="toggleCategory(c.key)"
        >
          <div class="stat-card-label">{{ c.label }}</div>
          <div class="stat-card-value">
            {{ categoryStats[c.key]?.total ?? 0 }}
            <span class="stat-card-suffix">启用 {{ categoryStats[c.key]?.enabled ?? 0 }}</span>
          </div>
          <div class="stat-card-hint">{{ c.hint }}</div>
        </el-card>
      </el-col>
    </el-row>

    <el-card>
      <!-- 搜索 + 类型/分类筛选 -->
      <div class="mc-toolbar">
        <el-input
          v-model="keyword"
          placeholder="搜索加速套件名称"
          clearable
          style="width: 260px"
          aria-label="搜索加速套件"
        />
        <el-select v-model="typeFilter" placeholder="类型筛选" clearable style="width: 160px">
          <el-option label="数据加速" value="data" />
          <el-option label="训练加速" value="training" />
          <el-option label="推理加速" value="inference" />
        </el-select>
        <el-select v-model="categoryFilter" placeholder="分类筛选" clearable style="width: 180px">
          <el-option
            v-for="o in categoryOptions"
            :key="o.value"
            :label="o.label"
            :value="o.value"
          />
        </el-select>
      </div>

      <PageState
        :loading="listLoading"
        :error="listError"
        :data="filteredSuites"
        :empty-text="categoryFilter ? '该分类下暂无加速套件。' : '暂无加速套件，还没有登记任何加速套件。'"
        @retry="fetchSuites"
      >
        <el-table :data="pagedSuites" row-key="id" border stripe style="width: 100%">
          <el-table-column prop="id" label="ID" width="70">
            <template #default="{ row }"><span class="mc-mono">{{ row.id }}</span></template>
          </el-table-column>
          <el-table-column prop="name" label="名称" min-width="140" />
          <el-table-column prop="description" label="描述" min-width="160" show-overflow-tooltip />
          <el-table-column label="类型" width="100">
            <template #default="{ row }">
              <el-tag>{{ row.type || '-' }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="version" label="版本" width="90" />
          <el-table-column label="状态" width="100">
            <template #default="{ row }">
              <el-tag :type="statusTagType(row.status)">{{ row.status || '-' }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column label="启用" width="90">
            <template #default="{ row }">
              <Can :roles="['admin', 'manager']">
                <el-switch
                  :model-value="!!row.enabled"
                  @change="(v: boolean) => handleToggle(row, v)"
                />
              </Can>
            </template>
          </el-table-column>
          <el-table-column label="分类" width="120">
            <template #default="{ row }">
              <el-tag v-if="categoryLabel(row.category)" type="primary">{{ categoryLabel(row.category) }}</el-tag>
              <span v-else>-</span>
            </template>
          </el-table-column>
          <el-table-column label="厂商" width="100">
            <template #default="{ row }">
              <el-tag v-if="row.vendor" type="success">{{ row.vendor }}</el-tag>
              <span v-else>-</span>
            </template>
          </el-table-column>
          <el-table-column label="操作" width="150" fixed="right">
            <template #default="{ row }">
              <el-button link type="primary" size="small" @click="openDetail(row)">详情</el-button>
              <Can :roles="['admin', 'manager']">
                <el-button link type="primary" size="small" @click="openEdit(row)">编辑</el-button>
              </Can>
            </template>
          </el-table-column>
        </el-table>
        <el-pagination
          v-model:current-page="page"
          v-model:page-size="pageSize"
          :total="filteredSuites.length"
          :page-sizes="[10, 20, 50]"
          layout="total, sizes, prev, pager, next"
          style="margin-top: 12px; justify-content: flex-end"
        />
      </PageState>
    </el-card>

    <!-- 编辑加速套件 Dialog -->
    <el-dialog
      v-model="editVisible"
      :title="`编辑加速套件 - ${editing?.name ?? ''}`"
      width="640px"
      destroy-on-close
    >
      <el-form ref="editFormRef" :model="editForm" :rules="editRules" label-position="top">
        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="名称" prop="name">
              <el-input v-model="editForm.name" placeholder="套件名称" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="类型" prop="type">
              <el-select v-model="editForm.type" placeholder="请选择类型" style="width: 100%">
                <el-option label="数据加速" value="data" />
                <el-option label="训练加速" value="training" />
                <el-option label="推理加速" value="inference" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="版本">
              <el-input v-model="editForm.version" placeholder="例如：v1.2.0" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="状态">
              <el-select v-model="editForm.status" placeholder="请选择状态" style="width: 100%">
                <el-option label="活跃" value="active" />
                <el-option label="非活跃" value="inactive" />
                <el-option label="错误" value="error" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="分类">
              <el-select v-model="editForm.category" placeholder="请选择分类" clearable style="width: 100%">
                <el-option
                  v-for="o in categoryOptions"
                  :key="o.value"
                  :label="o.label"
                  :value="o.value"
                />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="厂商">
              <el-select v-model="editForm.vendor" placeholder="请选择厂商" clearable style="width: 100%">
                <el-option v-for="o in vendorOptions" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="启用开关">
              <el-switch v-model="editForm.enabled" />
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="描述">
              <el-input v-model="editForm.description" type="textarea" :rows="2" placeholder="选填" />
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="Config JSON">
              <el-input
                v-model="editForm.config_json"
                type="textarea"
                :rows="6"
                placeholder='例如：{"runtime":"alluxio","cache_capacity_gb":100}'
              />
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="详情">
              <el-input v-model="editForm.details" type="textarea" :rows="3" placeholder="选填，补充说明" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <Can :roles="['admin', 'manager']">
          <el-button type="primary" :loading="saving" @click="handleSaveEdit">保存</el-button>
        </Can>
        <el-button @click="editVisible = false">取消</el-button>
      </template>
    </el-dialog>

    <!-- 加速套件详情 Drawer -->
    <el-drawer
      v-model="detailVisible"
      :title="`加速套件详情 - ${detail?.name ?? ''}`"
      size="560px"
    >
      <template v-if="detail">
        <el-descriptions :column="1" border size="small">
          <el-descriptions-item label="名称">{{ detail.name }}</el-descriptions-item>
          <el-descriptions-item label="类型">{{ detail.type || '-' }}</el-descriptions-item>
          <el-descriptions-item label="类别">{{ categoryLabel(detail.category) ?? detail.category ?? '-' }}</el-descriptions-item>
          <el-descriptions-item label="厂商">{{ detail.vendor ?? '-' }}</el-descriptions-item>
          <el-descriptions-item label="版本">{{ detail.version ?? '-' }}</el-descriptions-item>
          <el-descriptions-item label="状态">
            <el-tag :type="statusTagType(detail.status)">{{ detail.status || '-' }}</el-tag>
          </el-descriptions-item>
          <el-descriptions-item label="描述">{{ detail.description ?? '-' }}</el-descriptions-item>
        </el-descriptions>

        <el-card shadow="never" class="detail-card">
          <template #header>细分能力配置</template>
          <el-descriptions v-if="detailEntries.length" :column="1" size="small" border>
            <el-descriptions-item v-for="[k, v] in detailEntries" :key="k" :label="CONFIG_LABELS[k] ?? k">
              <el-tag v-if="typeof v === 'boolean'" :type="v ? 'success' : 'info'">{{ v ? '开' : '关' }}</el-tag>
              <span v-else>{{ String(v) }}</span>
            </el-descriptions-item>
          </el-descriptions>
          <el-empty v-else description="该套件尚未填写 config_json 能力参数。" :image-size="60" />
        </el-card>
      </template>
    </el-drawer>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, reactive } from 'vue'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import PageState from '@/components/PageState.vue'
import Can from '@/components/Can.vue'
import { accelerationApi } from '@/api'
import type { AccelerationSuite, GPUVendor } from '@/types'

const categoryOptions: { label: string; value: string }[] = [
  { label: '数据加速', value: 'fluid_cache' },
  { label: '分布式训练', value: 'distributed_training' },
  { label: '推理加速', value: 'inference' },
  { label: '通信优化', value: 'communication' },
]

const vendorOptions: { label: string; value: GPUVendor }[] = [
  { label: 'NVIDIA', value: 'nvidia' },
  { label: '燧原', value: 'enflame' },
  { label: '摩尔线程', value: 'moore_threads' },
  { label: '国产 X', value: 'domestic_x' },
]

const categoryCards = [
  { key: 'fluid_cache', label: '数据加速', hint: 'Fluid 缓存 / 预取 / 压缩' },
  { key: 'distributed_training', label: '分布式训练', hint: 'NCCL / DeepSpeed / 并行' },
  { key: 'inference', label: '推理加速', hint: 'TensorRT / 量化 / 批处理' },
  { key: 'communication', label: '通信优化', hint: '梯度通信 / 通信策略' },
]

const CONFIG_LABELS: Record<string, string> = {
  runtime: '运行时',
  cache_capacity_gb: '缓存容量(GB)',
  replicas: '副本数',
  medium_type: '缓存介质',
  prefetch_enabled: '数据预取',
  prefetch_policy: '预取策略',
  compression_enabled: '数据压缩',
  metadata_acceleration_enabled: '元数据加速',
  cache_hit_rate: '缓存命中率',
  parallel_strategy: '并行策略',
  world_size: '世界大小',
  tensor_parallel_size: '张量并行度',
  pipeline_stages: '流水线段数',
  deepspeed_enabled: 'DeepSpeed',
  megatron_enabled: 'Megatron-LM',
  communication_backend: '通信后端',
  nccl_config: 'NCCL 配置',
  gradient_compression: '梯度通信压缩',
  backend: '推理后端引擎',
  precision: '计算精度',
  quantization_enabled: '模型量化',
  batch_size: '批大小',
  dynamic_batching: '动态批处理',
  max_batch_size: '最大批大小',
  max_latency_ms: '最大时延(ms)',
  operator_fusion: '算子融合',
}

const suites = ref<AccelerationSuite[]>([])
const listLoading = ref(false)
const listError = ref('')
const keyword = ref('')
const typeFilter = ref('')
const categoryFilter = ref('')
const page = ref(1)
const pageSize = ref(10)

async function fetchSuites() {
  listLoading.value = true
  listError.value = ''
  try {
    suites.value = await accelerationApi.list()
  } catch (e) {
    listError.value = e instanceof Error ? e.message : '加载加速套件失败'
    suites.value = []
  } finally {
    listLoading.value = false
  }
}
fetchSuites()

const categoryStats = computed(() => {
  const stats: Record<string, { total: number; enabled: number }> = {}
  suites.value.forEach((s) => {
    const key = s.category ?? 'other'
    if (!stats[key]) stats[key] = { total: 0, enabled: 0 }
    stats[key].total += 1
    if (s.enabled) stats[key].enabled += 1
  })
  return stats
})

const filteredSuites = computed(() => {
  const kw = keyword.value.trim().toLowerCase()
  return suites.value.filter((s) => {
    const matchKw = !kw || s.name.toLowerCase().includes(kw) || (s.description ?? '').toLowerCase().includes(kw)
    const matchType = !typeFilter.value || s.type === typeFilter.value
    const matchCat = !categoryFilter.value || s.category === categoryFilter.value
    return matchKw && matchType && matchCat
  })
})

const pagedSuites = computed(() => {
  const start = (page.value - 1) * pageSize.value
  return filteredSuites.value.slice(start, start + pageSize.value)
})

function toggleCategory(key: string) {
  categoryFilter.value = categoryFilter.value === key ? '' : key
}

function categoryLabel(cat?: string) {
  return categoryOptions.find((o) => o.value === cat)?.label
}

// 启用 / 禁用切换
async function handleToggle(row: AccelerationSuite, enabled: boolean) {
  try {
    await accelerationApi.update(row.id, { enabled })
    row.enabled = enabled
    ElMessage.success(`加速套件${enabled ? '启用' : '禁用'}成功`)
  } catch {
    ElMessage.error('操作失败，请稍后重试')
  }
}

// 编辑 Dialog
interface SuiteForm {
  name: string
  description: string
  type: string
  version: string
  status: string
  enabled: boolean
  config_json: string
  category: string | undefined
  vendor: GPUVendor | undefined
  details: string
}

const editVisible = ref(false)
const editing = ref<AccelerationSuite | null>(null)
const saving = ref(false)
const editFormRef = ref<FormInstance>()

const emptyEditForm = (): SuiteForm => ({
  name: '',
  description: '',
  type: '',
  version: '',
  status: 'active',
  enabled: true,
  config_json: '',
  category: undefined,
  vendor: undefined,
  details: '',
})

const editForm = reactive<SuiteForm>(emptyEditForm())

const editRules: FormRules<SuiteForm> = {
  name: [{ required: true, message: '请输入名称', trigger: 'blur' }],
  type: [{ required: true, message: '请选择类型', trigger: 'change' }],
}

function openEdit(row: AccelerationSuite) {
  editing.value = row
  Object.assign(editForm, {
    name: row.name,
    description: row.description ?? '',
    type: row.type ?? '',
    version: row.version ?? '',
    status: row.status ?? 'active',
    enabled: !!row.enabled,
    config_json: row.config_json ?? '',
    category: row.category,
    vendor: row.vendor,
    details: row.details ?? '',
  })
  editVisible.value = true
}

async function handleSaveEdit() {
  if (!editFormRef.value || !editing.value) return
  await editFormRef.value.validate()
  saving.value = true
  try {
    await accelerationApi.update(editing.value.id, { ...editForm } as Partial<AccelerationSuite>)
    ElMessage.success('加速套件更新成功')
    editVisible.value = false
    await fetchSuites()
  } catch {
    ElMessage.error('更新失败，请稍后重试')
  } finally {
    saving.value = false
  }
}

// 详情 Drawer
const detailVisible = ref(false)
const detail = ref<AccelerationSuite | null>(null)

function openDetail(row: AccelerationSuite) {
  detail.value = row
  detailVisible.value = true
}

const detailConfig = computed<Record<string, unknown>>(() => {
  if (!detail.value?.config_json) return {}
  try {
    const v = JSON.parse(detail.value.config_json)
    return v && typeof v === 'object' ? (v as Record<string, unknown>) : {}
  } catch {
    return {}
  }
})

const detailEntries = computed<[string, unknown][]>(() => Object.entries(detailConfig.value))

function statusTagType(status?: string) {
  switch (status) {
    case 'active':
    case 'running':
      return 'success'
    case 'inactive':
    case 'paused':
      return 'info'
    case 'pending':
      return 'warning'
    case 'error':
    case 'failed':
      return 'danger'
    default:
      return 'info'
  }
}
</script>

<style scoped>
.stat-row {
  margin-bottom: 16px;
}
.stat-card {
  cursor: pointer;
  transition: border-color 0.2s;
}
.stat-card.is-active {
  border-color: var(--el-color-primary);
}
.stat-card-label {
  font-size: 13px;
  color: var(--mc-text-3, #909399);
}
.stat-card-value {
  font-size: 26px;
  font-weight: 600;
  margin: 6px 0 2px;
}
.stat-card-suffix {
  font-size: 12px;
  font-weight: 400;
  color: var(--mc-text-3, #909399);
  margin-left: 8px;
}
.stat-card-hint {
  font-size: 12px;
  color: var(--mc-text-3, #909399);
}
.mc-toolbar {
  display: flex;
  gap: 12px;
  margin-bottom: 16px;
}
.detail-card {
  margin-top: 16px;
}
.mc-mono {
  font-family: var(--mc-mono-font, monospace);
}
</style>
