// metaclouds-frontend/src/pages/JobManagement.tsx
﻿import { Can } from '../components/Can';
import React, { memo, useCallback, useMemo, useState } from 'react';
import { Card } from 'antd';
import ResponsiveTable from '../components/ResponsiveTable';
import type { ColumnsType } from 'antd/es/table';
import { Button, Space, App, Modal, Form, Input, Select, InputNumber, Tabs, Popconfirm, Switch, Drawer, Row, Col, Tag } from 'antd';
import { useGetJobsQuery, useCreateJobMutation, useCancelJobMutation, useGetPartitionsQuery } from '../store/api';
import { extractArrayData } from '../utils/api';
import { useLocation, useNavigate } from 'react-router-dom';
import { renderState, EmptyState } from '../components/States';
import { statusColor, statusText } from '../theme/tokens';
import type { Job, JobType, GPUVendor } from '../types';

/** 新建作业表单值 */
interface JobFormValues {
  name: string;
  type: JobType;
  gpus: number;
  description?: string;
  partition_id?: number;
  scheduler_type?: 'k8s_native' | 'slurm' | 'lsf' | 'sge';
  gpu_fraction?: number;
  gpu_memory_gb?: number;
  gpu_vendor?: GPUVendor;
  qos?: string;
  nodes_requested?: number;
  node_selector?: string;
  affinity?: string;
  tolerations?: string;
  elastic_enabled?: boolean;
  min_gpus?: number;
  max_gpus?: number;
  scaling_policy?: string;
  checkpoint_enabled?: boolean;
  checkpoint_interval_minutes?: number;
  max_retries?: number;
  fault_tolerance_level?: 'none' | 'node' | 'rack' | 'switch';
  topology_affinity?: 'node' | 'rack' | 'switch' | 'cluster';
  topology_anti_affinity?: boolean;
  network_requirement?: 'rdma' | 'ethernet' | 'any';
}

const JOB_TABS = [
  { key: '/job/list', label: '作业列表' },
  { key: '/job/queue', label: '任务队列' },
  { key: '/job/history', label: '历史记录' },
];

const SCHEDULER_TYPE_OPTIONS = [
  { label: 'K8s Native', value: 'k8s_native' },
  { label: 'Slurm', value: 'slurm' },
  { label: 'LSF', value: 'lsf' },
  { label: 'SGE', value: 'sge' },
];

const GPU_VENDOR_OPTIONS: { label: string; value: GPUVendor }[] = [
  { label: 'NVIDIA', value: 'nvidia' },
  { label: '燧原', value: 'enflame' },
  { label: '摩尔线程', value: 'moore_threads' },
  { label: '国产 X', value: 'domestic_x' },
];

const GPU_FRACTION_OPTIONS = [
  { label: '1 GPU', value: 1 },
  { label: '1/2 GPU', value: 0.5 },
  { label: '1/4 GPU', value: 0.25 },
];

const FAULT_TOLERANCE_OPTIONS = [
  { label: '无', value: 'none' },
  { label: '节点级', value: 'node' },
  { label: '机架级', value: 'rack' },
  { label: '交换机级', value: 'switch' },
];

const TOPOLOGY_AFFINITY_OPTIONS = [
  { label: '节点', value: 'node' },
  { label: '机架', value: 'rack' },
  { label: '交换机', value: 'switch' },
  { label: '集群', value: 'cluster' },
];

const NETWORK_REQUIREMENT_OPTIONS = [
  { label: 'RDMA', value: 'rdma' },
  { label: '以太网', value: 'ethernet' },
  { label: '任意', value: 'any' },
];

/** 状态 = 色点 + 文字，禁止仅用颜色表意。React.memo 避免父组件重渲染时无谓重绘。 */
const StatusCell: React.FC<{ status: string }> = memo(({ status }) => {
  const cls = ['running', 'pending', 'completed', 'failed'].includes(status) ? status : 'idle';
  return (
    <span className={`mc-status ${cls}`}>
      <i className="mc-status-dot" style={{ background: statusColor[status] }} />
      {statusText[status] ?? status}
    </span>
  );
});

const JobManagement: React.FC = () => {
  const { message } = App.useApp();
  const location = useLocation();
  const navigate = useNavigate();
  // 子路由驱动当前激活的页签；父路由 /job 默认落到"作业列表"
  const activeKey = location.pathname.startsWith('/job/') ? location.pathname : '/job/list';

  const { data: jobs, isLoading, error: jobsError, refetch } = useGetJobsQuery(undefined);
  const { data: partitions } = useGetPartitionsQuery({});
  const jobsData = extractArrayData<Job>(jobs);
  const partitionsData = partitions ?? [];
  const [createJob] = useCreateJobMutation();
  const [cancelJob] = useCancelJobMutation();
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [detailJob, setDetailJob] = useState<Job | null>(null);
  const [form] = Form.useForm<JobFormValues>();

  // 搜索 / 筛选
  const [searchText, setSearchText] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('');
  const [partitionFilter, setPartitionFilter] = useState<number | undefined>(undefined);

  const partitionName = useCallback(
    (id?: number) => partitionsData.find((p) => p.id === id)?.name ?? '-',
    [partitionsData],
  );

  // useCallback：稳定回调引用，避免传给子组件（Popconfirm/Button）时触发无谓重渲染
  const handleCreate = useCallback(async (values: JobFormValues) => {
    try {
      await createJob(values).unwrap();
      message.success('作业创建成功');
      setIsModalVisible(false);
      form.resetFields();
      refetch();
    } catch {
      message.error('作业创建失败，请检查必填项后重试');
    }
  }, [createJob, form, message, refetch]);

  const handleCancel = useCallback(async (id: number) => {
    try {
      await cancelJob(id).unwrap();
      message.success('作业已取消');
      refetch();
    } catch {
      message.error('作业取消失败，请稍后重试');
    }
  }, [cancelJob, message, refetch]);

  // 基础列定义用 useMemo 缓存：列配置不随渲染变化，避免每次渲染重建导致 Table 深比较失效
  const baseColumns = useMemo<ColumnsType<Job>>(() => [
    {
      title: 'ID',
      dataIndex: 'id',
      key: 'id',
      width: 90,
      render: (v: React.ReactNode) => <span className="mc-mono">{v}</span>,
    },
    {
      title: '名称',
      dataIndex: 'name',
      key: 'name',
      render: (v: string, record) => (
        <Button type="link" size="small" style={{ padding: 0 }} onClick={() => setDetailJob(record)}>
          {v}
        </Button>
      ),
    },
    { title: '类型', dataIndex: 'type', key: 'type' },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 110,
      render: (status: string) => <StatusCell status={status} />,
    },
    {
      title: 'GPU',
      dataIndex: 'gpus',
      key: 'gpus',
      width: 80,
      render: (v: React.ReactNode) => <span className="mc-num">{v}</span>,
    },
    {
      title: 'GPU分数',
      dataIndex: 'gpu_fraction',
      key: 'gpu_fraction',
      width: 90,
      render: (v: number) => (v != null ? <Tag color="blue">{v}</Tag> : '-'),
    },
    {
      title: '分区',
      dataIndex: 'partition_id',
      key: 'partition_id',
      width: 110,
      render: (v: number) => partitionName(v),
    },
    {
      title: '调度器',
      dataIndex: 'scheduler_type',
      key: 'scheduler_type',
      width: 110,
      render: (v: string) => {
        const opt = SCHEDULER_TYPE_OPTIONS.find((o) => o.value === v);
        return opt ? <Tag>{opt.label}</Tag> : '-';
      },
    },
    {
      title: '进度',
      dataIndex: 'progress',
      key: 'progress',
      width: 90,
      render: (progress: number) => <span className="mc-num">{progress}%</span>,
    },
    { title: '创建时间', dataIndex: 'created_at', key: 'created_at' },
    {
      title: '操作',
      key: 'action',
      width: 90,
      render: (_: unknown, record: Job) => (
        <Space>
          {record.status === 'running' || record.status === 'pending' ? (
            // 破坏性操作：二次确认，避免误触
            <Can perm="job:write">
            <Popconfirm
              title="取消该作业？"
              description="作业将立即终止且不可恢复。"
              okText="确认取消"
              cancelText="返回"
              okButtonProps={{ danger: true }}
              onConfirm={() => handleCancel(record.id)}
            >
              <Button type="link" danger size="small">
                取消
              </Button>
            </Popconfirm>
            </Can>
          ) : null}
        </Space>
      ),
    },
  ], [handleCancel, partitionName]);

  // 历史记录额外展示错误信息列
  const columns = useMemo(() => {
    if (activeKey === '/job/history') {
      return [
        ...baseColumns,
        {
          title: '错误信息',
          dataIndex: 'error_msg',
          key: 'error_msg',
          render: (v: string) => v || '-',
        },
      ];
    }
    return baseColumns;
  }, [activeKey, baseColumns]);

  // 按子路由过滤数据，使每个子菜单项对应真实数据集
  const currentData = useMemo(() => {
    let list = jobsData;
    if (activeKey === '/job/queue') {
      list = list.filter((j) => j.status === 'pending');
    } else if (activeKey === '/job/history') {
      list = list.filter((j) => ['completed', 'failed', 'cancelled'].includes(j.status));
    }
    // 关键词 + 状态 + 分区筛选
    const kw = searchText.trim().toLowerCase();
    return list.filter((j) => {
      const matchKw = !kw || j.name.toLowerCase().includes(kw) || (j.description ?? '').toLowerCase().includes(kw);
      const matchStatus = !statusFilter || j.status === statusFilter;
      const matchPartition = partitionFilter == null || j.partition_id === partitionFilter;
      return matchKw && matchStatus && matchPartition;
    });
  }, [activeKey, jobsData, searchText, statusFilter, partitionFilter]);

  const emptyText: Record<string, { title: string; desc: string }> = {
    '/job/list': { title: '还没有作业', desc: '提交第一个作业后，就可以在这里跟踪它的运行状态。' },
    '/job/queue': { title: '队列为空', desc: '当前没有排队中的作业，提交的作业会立即进入调度。' },
    '/job/history': { title: '暂无历史记录', desc: '作业完成、失败或取消后会归档到这里。' },
  };

  /** 三态守卫：错误 → 加载骨架屏 → 空态，其余情况渲染真实表格 */
  const renderTable = () => {
    const state = renderState({
      isLoading,
      error: jobsError,
      isEmpty: currentData.length === 0,
      onRetry: refetch,
      skeletonRows: 6,
      skeletonColumns: 7,
      empty: (
        <EmptyState
          title={emptyText[activeKey]?.title}
          description={emptyText[activeKey]?.desc}
          action={
            <Can perm="job:write">
              <Button type="primary" onClick={() => setIsModalVisible(true)}>
                新建作业
              </Button>
            </Can>
          }
        />
      ),
    });
    if (state) return state;

    return (
      <ResponsiveTable
        columns={columns}
        dataSource={currentData}
        rowKey="id"
        pagination={{ pageSize: 10, showTotal: (t) => `共 ${t} 条` }}
        scroll={{ x: 1200, y: 520 }}
        // 作业列表可能达数百行，启用 antd 虚拟滚动仅渲染可视区行，
        // 要求行高固定（本表格均为纯文本行，满足条件）。
        virtual
      />
    );
  };

  // 页头统计数据用 useMemo 缓存，避免每次渲染重复 filter
  const headerStats = useMemo(() => ({
    total: jobsData.length,
    pending: jobsData.filter((j) => j.status === 'pending').length,
    running: jobsData.filter((j) => j.status === 'running').length,
  }), [jobsData]);

  return (
    <div className="mc-page">
      <a href="#job-table" className="mc-skip-link">
        跳转到作业列表
      </a>
      <div className="mc-page-head">
        <div className="mc-page-head-main">
          <h1 className="mc-page-title">作业管理</h1>
          <p className="mc-page-desc">
            共 {headerStats.total} 个作业 · 排队{' '}
            {headerStats.pending} 个 · 运行中{' '}
            {headerStats.running} 个
          </p>
        </div>
        <div className="mc-page-head-extra">
          <Can perm="job:write">
            <Button type="primary" onClick={() => setIsModalVisible(true)}>
              新建作业
            </Button>
          </Can>
        </div>
      </div>

      <Card id="job-table">
        {/* 搜索 + 状态 / 分区筛选工具栏 */}
        <Row gutter={12} style={{ marginBottom: 16 }}>
          <Col flex="auto">
            <Input
              allowClear
              placeholder="搜索作业名称 / 描述"
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
            />
          </Col>
          <Col>
            <Select
              allowClear
              placeholder="状态"
              style={{ width: 130 }}
              value={statusFilter || undefined}
              onChange={(v) => setStatusFilter(v ?? '')}
              options={[
                { label: '排队中', value: 'pending' },
                { label: '运行中', value: 'running' },
                { label: '已完成', value: 'completed' },
                { label: '失败', value: 'failed' },
                { label: '已取消', value: 'cancelled' },
              ]}
            />
          </Col>
          <Col>
            <Select
              allowClear
              placeholder="分区"
              style={{ width: 150 }}
              value={partitionFilter}
              onChange={(v) => setPartitionFilter(v)}
              options={partitionsData.map((p) => ({ label: p.name, value: p.id }))}
            />
          </Col>
        </Row>
        <Tabs
          activeKey={activeKey}
          items={JOB_TABS.map((t) => ({ ...t, children: renderTable() }))}
          onChange={(key) => navigate(key)}
        />
      </Card>

      <Modal
        className="mc-modal-full"
        title="创建作业"
        open={isModalVisible}
        onCancel={() => setIsModalVisible(false)}
        footer={null}
        destroyOnHidden
        width={800}
      >
        <Form form={form} onFinish={handleCreate} layout="vertical">
          <Row gutter={16}>
            <Col span={12}>
              <Form.Item name="name" label="名称" rules={[{ required: true, message: '请输入作业名称' }]}>
                <Input placeholder="例如：llama3-70b-finetune" />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="type" label="类型" rules={[{ required: true, message: '请选择作业类型' }]}>
                <Select placeholder="请选择类型">
                  <Select.Option value="training">训练</Select.Option>
                  <Select.Option value="inference">推理</Select.Option>
                  <Select.Option value="batch">批处理</Select.Option>
                </Select>
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="gpus" label="GPU数量" rules={[{ required: true, message: '请输入 GPU 数量' }]}>
                <InputNumber min={1} max={8} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="gpu_fraction" label="GPU分数">
                <Select placeholder="请选择分数" allowClear options={GPU_FRACTION_OPTIONS} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="gpu_memory_gb" label="GPU显存(GB)">
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="gpu_vendor" label="GPU厂商">
                <Select placeholder="请选择厂商" allowClear options={GPU_VENDOR_OPTIONS} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="partition_id" label="分区">
                <Select
                  placeholder="请选择分区"
                  allowClear
                  options={partitionsData.map((p) => ({ label: p.name, value: p.id }))}
                />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="scheduler_type" label="调度器类型">
                <Select placeholder="请选择调度器" allowClear options={SCHEDULER_TYPE_OPTIONS} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="qos" label="QoS">
                <Input placeholder="例如：normal" />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="nodes_requested" label="请求节点数">
                <InputNumber min={1} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="network_requirement" label="网络需求">
                <Select placeholder="请选择网络需求" allowClear options={NETWORK_REQUIREMENT_OPTIONS} />
              </Form.Item>
            </Col>
            <Col span={24}>
              <Form.Item name="node_selector" label="节点选择器 (JSON)">
                <Input.TextArea rows={2} placeholder='例如：{"gpu-type":"a100"}' />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="affinity" label="亲和性 (JSON)">
                <Input.TextArea rows={2} placeholder="K8s affinity 配置" />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="tolerations" label="容忍度 (JSON)">
                <Input.TextArea rows={2} placeholder="K8s tolerations 配置" />
              </Form.Item>
            </Col>
            {/* 弹性训练 */}
            <Col span={8}>
              <Form.Item name="elastic_enabled" label="弹性训练" valuePropName="checked">
                <Switch />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="min_gpus" label="最小GPU">
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item
                name="max_gpus"
                label="最大GPU"
                dependencies={['min_gpus', 'elastic_enabled']}
                rules={[
                  ({ getFieldValue }) => ({
                    validator(_, value) {
                      if (getFieldValue('elastic_enabled') && value != null && getFieldValue('min_gpus') != null && value < getFieldValue('min_gpus')) {
                        return Promise.reject(new Error('最大GPU 不能小于 最小GPU'));
                      }
                      return Promise.resolve();
                    },
                  }),
                ]}
              >
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="scaling_policy" label="扩缩容策略">
                <Input placeholder="例如：cpu_utilization" />
              </Form.Item>
            </Col>
            {/* 容错训练 */}
            <Col span={8}>
              <Form.Item name="checkpoint_enabled" label="Checkpoint" valuePropName="checked">
                <Switch />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="checkpoint_interval_minutes" label="Checkpoint间隔(分钟)">
                <InputNumber min={1} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="max_retries" label="最大重试次数">
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="fault_tolerance_level" label="容错级别">
                <Select placeholder="请选择容错级别" allowClear options={FAULT_TOLERANCE_OPTIONS} />
              </Form.Item>
            </Col>
            {/* 拓扑感知 */}
            <Col span={8}>
              <Form.Item name="topology_affinity" label="拓扑亲和">
                <Select placeholder="请选择拓扑亲和" allowClear options={TOPOLOGY_AFFINITY_OPTIONS} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="topology_anti_affinity" label="拓扑反亲和" valuePropName="checked">
                <Switch />
              </Form.Item>
            </Col>
            <Col span={24}>
              <Form.Item name="description" label="描述">
                <Input.TextArea rows={3} placeholder="选填，便于后续追溯" />
              </Form.Item>
            </Col>
          </Row>
          <Form.Item style={{ marginBottom: 0 }}>
            <Space>
              <Can perm="job:write">
              <Button type="primary" htmlType="submit">
                创建
              </Button>
              </Can>
              <Button onClick={() => setIsModalVisible(false)}>取消</Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>

      {/* 作业详情 Drawer */}
      <Drawer
        title="作业详情"
        open={detailJob !== null}
        onClose={() => setDetailJob(null)}
        width={520}
      >
        {detailJob && (
          <div>
            <DetailRow label="名称" value={detailJob.name} />
            <DetailRow label="类型" value={detailJob.type ?? '-'} />
            <DetailRow label="状态" value={<StatusCell status={detailJob.status} />} />
            <DetailRow label="GPU数量" value={detailJob.gpus ?? '-'} />
            <DetailRow label="GPU分数" value={detailJob.gpu_fraction ?? '-'} />
            <DetailRow label="GPU显存" value={detailJob.gpu_memory_gb ? `${detailJob.gpu_memory_gb} GB` : '-'} />
            <DetailRow label="GPU厂商" value={detailJob.gpu_vendor ?? '-'} />
            <DetailRow label="分区" value={partitionName(detailJob.partition_id)} />
            <DetailRow label="调度器类型" value={detailJob.scheduler_type ?? '-'} />
            <DetailRow label="调度器作业ID" value={detailJob.scheduler_job_id ?? '-'} />
            <DetailRow label="QoS" value={detailJob.qos ?? '-'} />
            <DetailRow label="请求节点数" value={detailJob.nodes_requested ?? '-'} />
            <DetailRow label="弹性训练" value={detailJob.elastic_enabled ? '开启' : '关闭'} />
            {detailJob.elastic_enabled && (
              <>
                <DetailRow label="最小GPU" value={detailJob.min_gpus ?? '-'} />
                <DetailRow label="最大GPU" value={detailJob.max_gpus ?? '-'} />
                <DetailRow label="扩缩容策略" value={detailJob.scaling_policy ?? '-'} />
              </>
            )}
            <DetailRow label="Checkpoint" value={detailJob.checkpoint_enabled ? '开启' : '关闭'} />
            {detailJob.checkpoint_enabled && (
              <DetailRow label="Checkpoint间隔" value={`${detailJob.checkpoint_interval_minutes ?? '-'} 分钟`} />
            )}
            <DetailRow label="最大重试次数" value={detailJob.max_retries ?? '-'} />
            <DetailRow label="已重试次数" value={detailJob.retry_count ?? '-'} />
            <DetailRow label="容错级别" value={detailJob.fault_tolerance_level ?? '-'} />
            <DetailRow label="拓扑亲和" value={detailJob.topology_affinity ?? '-'} />
            <DetailRow label="拓扑反亲和" value={detailJob.topology_anti_affinity ? '开启' : '关闭'} />
            <DetailRow label="网络需求" value={detailJob.network_requirement ?? '-'} />
            <DetailRow label="节点选择器" value={detailJob.node_selector ?? '-'} />
            <DetailRow label="亲和性" value={detailJob.affinity ?? '-'} />
            <DetailRow label="容忍度" value={detailJob.tolerations ?? '-'} />
            <DetailRow label="进度" value={`${detailJob.progress ?? 0}%`} />
            <DetailRow label="描述" value={detailJob.description ?? '-'} />
          </div>
        )}
      </Drawer>
    </div>
  );
};

/** 详情行 */
const DetailRow: React.FC<{ label: string; value: React.ReactNode }> = ({ label, value }) => (
  <div style={{ display: 'flex', padding: '8px 0', borderBottom: '1px solid var(--mc-border)' }}>
    <span style={{ width: 130, color: 'var(--mc-text-3)', flexShrink: 0 }}>{label}</span>
    <span style={{ flex: 1, wordBreak: 'break-all' }}>{value}</span>
  </div>
);

export default JobManagement;

// metaclouds-frontend-vue/src/pages/JobManagement.vue
<template>
  <div class="mc-page">
    <!-- 页头：统计 + 新建按钮 -->
    <div class="mc-page-head">
      <div class="mc-page-head-main">
        <h1 class="mc-page-title">作业管理</h1>
        <p class="mc-page-desc">
          共 {{ stats.total }} 个作业 · 排队 {{ stats.pending }} 个 · 运行中 {{ stats.running }} 个
        </p>
      </div>
      <div class="mc-page-head-extra">
        <Can :roles="['admin', 'manager']">
          <el-button type="primary" @click="openCreate">新建作业</el-button>
        </Can>
      </div>
    </div>

    <el-card id="job-table">
      <!-- 搜索 + 状态 / 类型 / 分区 筛选工具栏 -->
      <div class="mc-flow mc-mb">
        <el-input
          v-model="searchText"
          placeholder="搜索作业名称 / 描述"
          clearable
          style="width: 240px"
          aria-label="搜索作业"
        />
        <el-select v-model="statusFilter" placeholder="状态" clearable style="width: 130px">
          <el-option v-for="o in STATUS_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
        </el-select>
        <el-select v-model="typeFilter" placeholder="类型" clearable style="width: 130px">
          <el-option v-for="o in TYPE_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
        </el-select>
        <el-select v-model="partitionFilter" placeholder="分区" clearable style="width: 160px">
          <el-option v-for="p in partitions" :key="p.id" :label="p.name" :value="p.id" />
        </el-select>
      </div>

      <!-- 子路由驱动的 Tab 切换 -->
      <el-tabs :model-value="activeTab" @tab-change="onTabChange">
        <el-tab-pane label="作业列表" name="/job/list" />
        <el-tab-pane label="任务队列" name="/job/queue" />
        <el-tab-pane label="历史记录" name="/job/history" />
      </el-tabs>

      <!-- 三态守卫：loading / error / empty，其余渲染表格 -->
      <PageState
        :loading="jobsLoading"
        :error="jobsError"
        :data="pagedJobs"
        :empty-text="emptyText"
        @retry="loadJobs"
      >
        <el-table :data="pagedJobs" stripe style="width: 100%" row-key="id">
          <el-table-column prop="id" label="ID" width="80">
            <template #default="{ row }"><span class="mc-mono">{{ row.id }}</span></template>
          </el-table-column>
          <el-table-column label="名称" min-width="160">
            <template #default="{ row }">
              <el-button type="primary" link @click="openDetail(row)">{{ row.name }}</el-button>
            </template>
          </el-table-column>
          <el-table-column prop="type" label="类型" width="90">
            <template #default="{ row }">{{ row.type || '-' }}</template>
          </el-table-column>
          <el-table-column label="状态" width="110">
            <template #default="{ row }">
              <span class="mc-status" :class="statusClass(row.status)">
                <i class="mc-status-dot" />{{ statusText(row.status) }}
              </span>
            </template>
          </el-table-column>
          <el-table-column prop="priority" label="优先级" width="90">
            <template #default="{ row }">
              <el-tag v-if="row.priority != null" :type="priorityTagType(row.priority)">{{ priorityText(row.priority) }}</el-tag>
              <span v-else>-</span>
            </template>
          </el-table-column>
          <el-table-column prop="gpus" label="GPU数" width="80">
            <template #default="{ row }"><span class="mc-num">{{ row.gpus ?? '-' }}</span></template>
          </el-table-column>
          <el-table-column prop="cpus" label="CPU数" width="80">
            <template #default="{ row }"><span class="mc-num">{{ row.cpus ?? '-' }}</span></template>
          </el-table-column>
          <el-table-column prop="memory" label="内存(GB)" width="100">
            <template #default="{ row }"><span class="mc-num">{{ row.memory ?? '-' }}</span></template>
          </el-table-column>
          <el-table-column label="进度" width="160">
            <template #default="{ row }">
              <el-progress v-if="row.status === 'running' || row.status === 'pending'"
                :percentage="row.progress ?? 0" :stroke-width="10" />
              <span v-else class="mc-num">{{ row.progress ?? 0 }}%</span>
            </template>
          </el-table-column>
          <el-table-column label="分区" width="120">
            <template #default="{ row }">{{ partitionName(row.partition_id) }}</template>
          </el-table-column>
          <el-table-column label="调度器" width="120">
            <template #default="{ row }">
              <el-tag v-if="schedulerLabel(row.scheduler_type)">{{ schedulerLabel(row.scheduler_type) }}</el-tag>
              <span v-else>-</span>
            </template>
          </el-table-column>
          <el-table-column prop="created_at" label="创建时间" width="170">
            <template #default="{ row }">{{ row.created_at || '-' }}</template>
          </el-table-column>
          <el-table-column v-if="activeTab === '/job/history'" label="错误信息" min-width="160">
            <template #default="{ row }">{{ row.error_msg || '-' }}</template>
          </el-table-column>
          <el-table-column label="操作" width="240" fixed="right">
            <template #default="{ row }">
              <Can :roles="['admin', 'manager']">
                <el-button v-if="row.status === 'pending'" type="primary" link size="small" @click="handleSubmitToK8S(row)">
                  提交到K8S
                </el-button>
              </Can>
              <el-button v-if="row.status === 'running' || row.status === 'pending'" type="danger" link size="small" @click="handleCancel(row)">
                取消
              </el-button>
              <el-button type="primary" link size="small" @click="openDetail(row)">查看详情</el-button>
            </template>
          </el-table-column>
        </el-table>
        <el-pagination
          class="mc-mt"
          layout="total, sizes, prev, pager, next"
          :total="filteredJobs.length"
          v-model:current-page="page.current"
          v-model:page-size="page.size"
          :page-sizes="[10, 20, 50]"
          background
        />
      </PageState>
    </el-card>

    <!-- 创建作业 Dialog -->
    <el-dialog v-model="createVisible" title="创建作业" width="860px" destroy-on-close @closed="resetForm">
      <el-form ref="formRef" :model="form" :rules="rules" label-width="130px">
        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="名称" prop="name">
              <el-input v-model="form.name" placeholder="例如：llama3-70b-finetune" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="类型" prop="type">
              <el-select v-model="form.type" placeholder="请选择类型" style="width: 100%">
                <el-option label="训练" value="training" />
                <el-option label="推理" value="inference" />
                <el-option label="批处理" value="batch" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="优先级" prop="priority">
              <el-select v-model="form.priority" placeholder="请选择优先级" style="width: 100%">
                <el-option v-for="o in PRIORITY_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="GPU数量" prop="gpus">
              <el-input-number v-model="form.gpus" :min="1" :max="8" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="CPU数">
              <el-input-number v-model="form.cpus" :min="1" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="内存(GB)">
              <el-input-number v-model="form.memory" :min="1" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="GPU分数">
              <el-select v-model="form.gpu_fraction" placeholder="请选择分数" clearable style="width: 100%">
                <el-option v-for="o in GPU_FRACTION_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="GPU显存(GB)">
              <el-input-number v-model="form.gpu_memory_gb" :min="0" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="GPU厂商">
              <el-select v-model="form.gpu_vendor" placeholder="请选择厂商" clearable style="width: 100%">
                <el-option v-for="o in GPU_VENDOR_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="分区">
              <el-select v-model="form.partition_id" placeholder="请选择分区" clearable style="width: 100%">
                <el-option v-for="p in partitions" :key="p.id" :label="p.name" :value="p.id" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="调度器类型">
              <el-select v-model="form.scheduler_type" placeholder="请选择调度器" clearable style="width: 100%">
                <el-option v-for="o in SCHEDULER_TYPE_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="QoS">
              <el-input v-model="form.qos" placeholder="例如：normal" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="请求节点数">
              <el-input-number v-model="form.nodes_requested" :min="1" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="网络需求">
              <el-select v-model="form.network_requirement" placeholder="请选择网络需求" clearable style="width: 100%">
                <el-option v-for="o in NETWORK_REQUIREMENT_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="节点选择器 (JSON)">
              <el-input v-model="form.node_selector" type="textarea" :rows="2" placeholder='例如：{"gpu-type":"a100"}' />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="亲和性 (JSON)">
              <el-input v-model="form.affinity" type="textarea" :rows="2" placeholder="K8s affinity 配置" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="容忍度 (JSON)">
              <el-input v-model="form.tolerations" type="textarea" :rows="2" placeholder="K8s tolerations 配置" />
            </el-form-item>
          </el-col>
          <!-- 弹性训练 -->
          <el-col :span="8">
            <el-form-item label="弹性训练">
              <el-switch v-model="form.elastic_enabled" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="最小GPU">
              <el-input-number v-model="form.min_gpus" :min="0" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="最大GPU">
              <el-input-number v-model="form.max_gpus" :min="0" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="扩缩容策略">
              <el-input v-model="form.scaling_policy" placeholder="例如：cpu_utilization" />
            </el-form-item>
          </el-col>
          <!-- 容错训练 -->
          <el-col :span="8">
            <el-form-item label="Checkpoint">
              <el-switch v-model="form.checkpoint_enabled" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="Checkpoint间隔(分钟)">
              <el-input-number v-model="form.checkpoint_interval_minutes" :min="1" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="最大重试次数">
              <el-input-number v-model="form.max_retries" :min="0" style="width: 100%" />
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="容错级别">
              <el-select v-model="form.fault_tolerance_level" placeholder="请选择容错级别" clearable style="width: 100%">
                <el-option v-for="o in FAULT_TOLERANCE_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
          <!-- 拓扑感知 -->
          <el-col :span="8">
            <el-form-item label="拓扑亲和">
              <el-select v-model="form.topology_affinity" placeholder="请选择拓扑亲和" clearable style="width: 100%">
                <el-option v-for="o in TOPOLOGY_AFFINITY_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="8">
            <el-form-item label="拓扑反亲和">
              <el-switch v-model="form.topology_anti_affinity" />
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="描述">
              <el-input v-model="form.description" type="textarea" :rows="3" placeholder="选填，便于后续追溯" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <el-button @click="createVisible = false">取消</el-button>
        <Can :roles="['admin', 'manager']">
          <el-button type="primary" :loading="creating" @click="submitCreate">创建</el-button>
        </Can>
      </template>
    </el-dialog>

    <!-- 作业详情 Dialog（含 Checkpoint 子视图） -->
    <el-dialog v-model="detailVisible" title="作业详情" width="720px" destroy-on-close>
      <template v-if="detailJob">
        <el-descriptions :column="2" border size="small">
          <el-descriptions-item label="名称">{{ detailJob.name }}</el-descriptions-item>
          <el-descriptions-item label="类型">{{ detailJob.type || '-' }}</el-descriptions-item>
          <el-descriptions-item label="状态">
            <span class="mc-status" :class="statusClass(detailJob.status)">
              <i class="mc-status-dot" />{{ statusText(detailJob.status) }}
            </span>
          </el-descriptions-item>
          <el-descriptions-item label="优先级">{{ priorityText(detailJob.priority) }}</el-descriptions-item>
          <el-descriptions-item label="GPU数量">{{ detailJob.gpus ?? '-' }}</el-descriptions-item>
          <el-descriptions-item label="GPU分数">{{ detailJob.gpu_fraction ?? '-' }}</el-descriptions-item>
          <el-descriptions-item label="CPU数">{{ detailJob.cpus ?? '-' }}</el-descriptions-item>
          <el-descriptions-item label="内存(GB)">{{ detailJob.memory ?? '-' }}</el-descriptions-item>
          <el-descriptions-item label="GPU显存">{{ detailJob.gpu_memory_gb ? detailJob.gpu_memory_gb + ' GB' : '-' }}</el-descriptions-item>
          <el-descriptions-item label="GPU厂商">{{ detailJob.gpu_vendor || '-' }}</el-descriptions-item>
          <el-descriptions-item label="分区">{{ partitionName(detailJob.partition_id) }}</el-descriptions-item>
          <el-descriptions-item label="调度器类型">{{ detailJob.scheduler_type || '-' }}</el-descriptions-item>
          <el-descriptions-item label="调度器作业ID">{{ detailJob.scheduler_job_id || '-' }}</el-descriptions-item>
          <el-descriptions-item label="QoS">{{ detailJob.qos || '-' }}</el-descriptions-item>
          <el-descriptions-item label="请求节点数">{{ detailJob.nodes_requested ?? '-' }}</el-descriptions-item>
          <el-descriptions-item label="弹性训练">{{ detailJob.elastic_enabled ? '开启' : '关闭' }}</el-descriptions-item>
          <template v-if="detailJob.elastic_enabled">
            <el-descriptions-item label="最小GPU">{{ detailJob.min_gpus ?? '-' }}</el-descriptions-item>
            <el-descriptions-item label="最大GPU">{{ detailJob.max_gpus ?? '-' }}</el-descriptions-item>
          </template>
          <el-descriptions-item label="Checkpoint">{{ detailJob.checkpoint_enabled ? '开启' : '关闭' }}</el-descriptions-item>
          <el-descriptions-item v-if="detailJob.checkpoint_enabled" label="Checkpoint间隔">
            {{ detailJob.checkpoint_interval_minutes ?? '-' }} 分钟
          </el-descriptions-item>
          <el-descriptions-item label="最大重试次数">{{ detailJob.max_retries ?? '-' }}</el-descriptions-item>
          <el-descriptions-item label="已重试次数">{{ detailJob.retry_count ?? '-' }}</el-descriptions-item>
          <el-descriptions-item label="容错级别">{{ detailJob.fault_tolerance_level || '-' }}</el-descriptions-item>
          <el-descriptions-item label="拓扑亲和">{{ detailJob.topology_affinity || '-' }}</el-descriptions-item>
          <el-descriptions-item label="拓扑反亲和">{{ detailJob.topology_anti_affinity ? '开启' : '关闭' }}</el-descriptions-item>
          <el-descriptions-item label="网络需求">{{ detailJob.network_requirement || '-' }}</el-descriptions-item>
          <el-descriptions-item label="节点选择器" :span="2">{{ detailJob.node_selector || '-' }}</el-descriptions-item>
          <el-descriptions-item label="亲和性" :span="2">{{ detailJob.affinity || '-' }}</el-descriptions-item>
          <el-descriptions-item label="容忍度" :span="2">{{ detailJob.tolerations || '-' }}</el-descriptions-item>
          <el-descriptions-item label="进度">{{ detailJob.progress ?? 0 }}%</el-descriptions-item>
          <el-descriptions-item label="描述" :span="2">{{ detailJob.description || '-' }}</el-descriptions-item>
        </el-descriptions>

        <!-- Checkpoint 列表子视图 -->
        <el-divider content-position="left">Checkpoint 记录</el-divider>
        <el-table :data="checkpoints" size="small" stripe>
          <el-table-column prop="id" label="ID" width="70" />
          <el-table-column prop="path" label="路径" min-width="200" show-overflow-tooltip />
          <el-table-column prop="step" label="Step" width="80" />
          <el-table-column prop="epoch" label="Epoch" width="80" />
          <el-table-column prop="size_mb" label="大小(MB)" width="100" />
          <el-table-column prop="format" label="格式" width="110" />
          <el-table-column label="状态" width="110">
            <template #default="{ row }">
              <el-tag :type="checkpointTagType(row.status)">{{ row.status || '-' }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column label="最新" width="80">
            <template #default="{ row }">
              <el-tag v-if="row.is_latest" type="success">最新</el-tag>
            </template>
          </el-table-column>
        </el-table>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import { jobApi, partitionApi, checkpointApi } from '@/api'
import type { Job, JobStatus, JobType, JobPriority, GPUVendor, Checkpoint, Partition } from '@/types'
import { useFetch, useMutation } from '@/utils/useFetch'
import PageState from '@/components/PageState.vue'
import Can from '@/components/Can.vue'

const route = useRoute()
const router = useRouter()

// ---------- 常量 ----------
const STATUS_OPTIONS: { label: string; value: JobStatus }[] = [
  { label: '排队中', value: 'pending' },
  { label: '运行中', value: 'running' },
  { label: '已完成', value: 'completed' },
  { label: '失败', value: 'failed' },
  { label: '已取消', value: 'cancelled' },
]
const TYPE_OPTIONS: { label: string; value: JobType }[] = [
  { label: '训练', value: 'training' },
  { label: '推理', value: 'inference' },
  { label: '批处理', value: 'batch' },
]
const PRIORITY_OPTIONS: { label: string; value: JobPriority }[] = [
  { label: '低', value: 0 },
  { label: '中', value: 1 },
  { label: '高', value: 2 },
  { label: '紧急', value: 3 },
]
const SCHEDULER_TYPE_OPTIONS = [
  { label: 'K8s Native', value: 'k8s_native' },
  { label: 'Slurm', value: 'slurm' },
  { label: 'LSF', value: 'lsf' },
  { label: 'SGE', value: 'sge' },
]
const GPU_VENDOR_OPTIONS: { label: string; value: GPUVendor }[] = [
  { label: 'NVIDIA', value: 'nvidia' },
  { label: '燧原', value: 'enflame' },
  { label: '摩尔线程', value: 'moore_threads' },
  { label: '国产 X', value: 'domestic_x' },
]
const GPU_FRACTION_OPTIONS = [
  { label: '1 GPU', value: 1 },
  { label: '1/2 GPU', value: 0.5 },
  { label: '1/4 GPU', value: 0.25 },
]
const FAULT_TOLERANCE_OPTIONS = [
  { label: '无', value: 'none' },
  { label: '节点级', value: 'node' },
  { label: '机架级', value: 'rack' },
  { label: '交换机级', value: 'switch' },
]
const TOPOLOGY_AFFINITY_OPTIONS = [
  { label: '节点', value: 'node' },
  { label: '机架', value: 'rack' },
  { label: '交换机', value: 'switch' },
  { label: '集群', value: 'cluster' },
]
const NETWORK_REQUIREMENT_OPTIONS = [
  { label: 'RDMA', value: 'rdma' },
  { label: '以太网', value: 'ethernet' },
  { label: '任意', value: 'any' },
]

// ---------- 数据 ----------
const { data: jobsRaw, loading: jobsLoading, error: jobsError, execute: loadJobs } = useFetch<Job[]>(() => jobApi.list())
const { data: partitionsRaw, execute: loadPartitions } = useFetch<Partition[]>(() => partitionApi.list())
const jobs = computed<Job[]>(() => jobsRaw.value ?? [])
const partitions = computed<Partition[]>(() => partitionsRaw.value ?? [])

const createMut = useMutation<Job, Partial<Job>>((data) => jobApi.create(data))
const cancelMut = useMutation<void, number>((id) => jobApi.cancel(id))
const submitMut = useMutation<void, number>((id) => jobApi.submitToK8S(id))
const creating = computed(() => createMut.loading.value)

// ---------- Tab 由 route.path 决定 ----------
const activeTab = computed(() => {
  const p = route.path
  if (p.startsWith('/job/queue')) return '/job/queue'
  if (p.startsWith('/job/history')) return '/job/history'
  return '/job/list'
})
function onTabChange(name: string) {
  router.push(name)
}

// ---------- 搜索 / 筛选 ----------
const searchText = ref('')
const statusFilter = ref<JobStatus | ''>('')
const typeFilter = ref<JobType | ''>('')
const partitionFilter = ref<number | undefined>(undefined)

const emptyText = computed(() => {
  if (activeTab.value === '/job/queue') return '队列为空：当前没有排队中的作业'
  if (activeTab.value === '/job/history') return '暂无历史记录：作业完成、失败或取消后会归档到这里'
  return '还没有作业：提交第一个作业后，就可以在这里跟踪它的运行状态'
})

const filteredJobs = computed(() => {
  let list = jobs.value
  if (activeTab.value === '/job/queue') {
    list = list.filter((j) => j.status === 'pending')
  } else if (activeTab.value === '/job/history') {
    list = list.filter((j) => ['completed', 'failed', 'cancelled'].includes(j.status))
  }
  const kw = searchText.value.trim().toLowerCase()
  return list.filter((j) => {
    const matchKw = !kw || j.name.toLowerCase().includes(kw) || (j.description ?? '').toLowerCase().includes(kw)
    const matchStatus = !statusFilter.value || j.status === statusFilter.value
    const matchType = !typeFilter.value || j.type === typeFilter.value
    const matchPartition = partitionFilter.value == null || j.partition_id === partitionFilter.value
    return matchKw && matchStatus && matchType && matchPartition
  })
})

// ---------- 分页 ----------
const page = reactive({ current: 1, size: 10 })
const pagedJobs = computed(() => {
  const start = (page.current - 1) * page.size
  return filteredJobs.value.slice(start, start + page.size)
})

// ---------- 页头统计 ----------
const stats = computed(() => ({
  total: jobs.value.length,
  pending: jobs.value.filter((j) => j.status === 'pending').length,
  running: jobs.value.filter((j) => j.status === 'running').length,
}))

// ---------- 展示辅助 ----------
function statusClass(s?: string) {
  return ['running', 'pending', 'completed', 'failed', 'cancelled'].includes(s ?? '') ? (s as string) : 'idle'
}
function statusText(s?: string) {
  const map: Record<string, string> = {
    pending: '排队中', running: '运行中', completed: '已完成', failed: '失败', cancelled: '已取消',
  }
  return map[s ?? ''] ?? s ?? '-'
}
function priorityText(p?: number) {
  const map: Record<number, string> = { 0: '低', 1: '中', 2: '高', 3: '紧急' }
  return p == null ? '-' : map[p] ?? String(p)
}
function priorityTagType(p?: number) {
  if (p === 3) return 'danger'
  if (p === 2) return 'warning'
  if (p === 1) return 'primary'
  return 'info'
}
function partitionName(id?: number) {
  if (id == null) return '-'
  return partitions.value.find((p) => p.id === id)?.name ?? '-'
}
function schedulerLabel(v?: string) {
  return SCHEDULER_TYPE_OPTIONS.find((o) => o.value === v)?.label
}
function checkpointTagType(s?: string) {
  if (s === 'completed') return 'success'
  if (s === 'failed' || s === 'corrupted') return 'danger'
  if (s === 'in_progress') return 'warning'
  return 'info'
}

// ---------- 创建作业 ----------
const createVisible = ref(false)
const formRef = ref<FormInstance>()
const form = reactive({
  name: '',
  type: 'training' as JobType,
  priority: 1 as JobPriority,
  gpus: 1,
  cpus: undefined as number | undefined,
  memory: undefined as number | undefined,
  description: '',
  partition_id: undefined as number | undefined,
  scheduler_type: undefined as string | undefined,
  gpu_fraction: undefined as number | undefined,
  gpu_memory_gb: undefined as number | undefined,
  gpu_vendor: undefined as GPUVendor | undefined,
  qos: '',
  nodes_requested: undefined as number | undefined,
  node_selector: '',
  affinity: '',
  tolerations: '',
  elastic_enabled: false,
  min_gpus: undefined as number | undefined,
  max_gpus: undefined as number | undefined,
  scaling_policy: '',
  checkpoint_enabled: false,
  checkpoint_interval_minutes: undefined as number | undefined,
  max_retries: undefined as number | undefined,
  fault_tolerance_level: undefined as string | undefined,
  topology_affinity: undefined as string | undefined,
  topology_anti_affinity: false,
  network_requirement: undefined as string | undefined,
})
const rules: FormRules = {
  name: [{ required: true, message: '请输入作业名称', trigger: 'blur' }],
  type: [{ required: true, message: '请选择作业类型', trigger: 'change' }],
  gpus: [{ required: true, message: '请输入 GPU 数量', trigger: 'blur' }],
}

function openCreate() {
  createVisible.value = true
  void loadPartitions()
}
function resetForm() {
  formRef.value?.resetFields()
}
async function submitCreate() {
  if (!formRef.value) return
  await formRef.value.validate()
  try {
    await createMut.mutate({ ...form } as Partial<Job>)
    ElMessage.success('作业创建成功')
    createVisible.value = false
    loadJobs()
  } catch {
    ElMessage.error('作业创建失败，请检查必填项后重试')
  }
}

// ---------- 取消 / 提交 K8S ----------
async function handleCancel(row: Job) {
  try {
    await ElMessageBox.confirm('作业将立即终止且不可恢复。', '取消该作业？', {
      confirmButtonText: '确认取消',
      cancelButtonText: '返回',
      type: 'warning',
    })
  } catch {
    return
  }
  try {
    await cancelMut.mutate(row.id)
    ElMessage.success('作业已取消')
    loadJobs()
  } catch {
    ElMessage.error('作业取消失败，请稍后重试')
  }
}
async function handleSubmitToK8S(row: Job) {
  try {
    await submitMut.mutate(row.id)
    ElMessage.success('作业已提交到K8S')
    loadJobs()
  } catch {
    ElMessage.error('提交作业到K8S失败')
  }
}

// ---------- 详情 + Checkpoint ----------
const detailVisible = ref(false)
const detailJob = ref<Job | null>(null)
const checkpoints = ref<Checkpoint[]>([])

async function openDetail(row: Job) {
  detailJob.value = row
  detailVisible.value = true
  checkpoints.value = []
  try {
    checkpoints.value = await checkpointApi.list({ job_id: row.id })
  } catch {
    ElMessage.warning('Checkpoint 加载失败')
  }
}
</script>
